/**
 * Component registry — the ONLY components the page renderer may instantiate.
 *
 * Keys are the locked-down A1 component names from `ComponentType`; values are
 * the real A1 React components. Anything not in this map renders the
 * `UnsupportedComponent` fallback in `pageRenderer.tsx`. Arbitrary HTML tags
 * (`div`, `p`, `span`, …) are intentionally NOT supported.
 *
 * To allow a new component: add its name to `ComponentType` in `pageTypes.ts`
 * and add the real component here. The `Record<ComponentType, …>` typing forces
 * this map to cover exactly the names in the contract.
 */
import {
  Accordion,
  Autocomplete,
  Banner,
  Bleed,
  Blockquote,
  BottomDrawer,
  Breadcrumb,
  Button,
  ButtonContainer,
  Calendar,
  Card,
  CheckboxGroup,
  ChoiceGroup,
  CircularProgress,
  Cluster,
  Code,
  AreaChart,
  BarChart,
  ComposedChart,
  CreditCardField,
  DateField,
  DefinitionList,
  Divider,
  FieldRow,
  Figure,
  Fieldset,
  FunnelChart,
  Grid,
  Heading,
  Icon,
  IconButton,
  InlineEditable,
  Inset,
  Link,
  LineChart,
  List,
  ListItem,
  MessageBadge,
  MessageEmptyState,
  Node,
  NumberField,
  PageNav,
  Pagination,
  Paragraph,
  PhoneField,
  PieChart,
  RadarChart,
  RadialBarChart,
  RadioGroup,
  SankeyChart,
  ScatterChart,
  SearchField,
  Section,
  SectionSeparator,
  SegmentedControl,
  SelectField,
  Slider,
  Spacer,
  Stack,
  Stat,
  StatusBar,
  StepTracker,
  StickyActions,
  SunburstChart,
  Switch,
  TextField,
  TextareaField,
  TimeField,
  TopHeader,
  TreemapChart,
  ZipField,
} from '@gtivr4/a1-design-system-react';
import type { ComponentType as ReactComponentType } from 'react';
import type { ComponentType } from './pageTypes';
import {
  EditorActionTiles,
  EditorBottomSheet,
  EditorCanvas,
  EditorChipGroup,
  EditorContextMenu,
  EditorDataTable,
  EditorDialog,
  EditorInline,
  EditorMenu,
  EditorNotification,
  EditorOutlet,
  EditorPageLayout,
  EditorSideNav,
  EditorSlot,
  EditorSnackbar,
  EditorTabs,
  EditorToolbar,
  EditorTreeMenu,
} from './editorComponents.jsx';

export const componentRegistry: Record<ComponentType, ReactComponentType<any>> = {
  // Layout
  PageLayout: EditorPageLayout,
  Section,
  SectionSeparator,
  Stack,
  Grid,
  Cluster,
  Canvas: EditorCanvas,
  Card,
  Bleed,
  Inset,
  Spacer,
  ButtonContainer,
  // Typography & media
  Heading,
  Paragraph,
  Blockquote,
  Code,
  Divider,
  Inline: EditorInline,
  List,
  ListItem,
  Icon,
  Figure,
  // Navigation & actions
  Link,
  Button,
  ActionTiles: EditorActionTiles,
  ChipGroup: EditorChipGroup,
  IconButton,
  Switch,
  SegmentedControl,
  // Feedback
  Banner,
  MessageBadge,
  MessageEmptyState,
  Notification: EditorNotification,
  Snackbar: EditorSnackbar,
  StatusBar,
  CircularProgress,
  StepTracker,
  // Inputs
  TextField,
  SearchField,
  TextareaField,
  SelectField,
  Autocomplete,
  NumberField,
  DateField,
  TimeField,
  PhoneField,
  ZipField,
  CreditCardField,
  InlineEditable,
  Fieldset,
  CheckboxGroup,
  RadioGroup,
  ChoiceGroup,
  // Data
  Stat,
  LineChart,
  BarChart,
  AreaChart,
  ComposedChart,
  PieChart,
  ScatterChart,
  RadarChart,
  RadialBarChart,
  FunnelChart,
  TreemapChart,
  SankeyChart,
  SunburstChart,
  DefinitionList,
  Pagination,
  Calendar,
  Node,
  // Navigation
  Breadcrumb,
  SideNav: EditorSideNav,
  TopHeader,
  BottomDrawer,
  BottomSheet: EditorBottomSheet,
  StickyActions,
  PageNav,
  // Disclosure
  Accordion,
  Dialog: EditorDialog,
  Menu: EditorMenu,
  ContextMenu: EditorContextMenu,
  // Actions & controls (config-as-props adapters + real components)
  Slider,
  Tabs: EditorTabs,
  Toolbar: EditorToolbar,
  // Inputs
  FieldRow,
  // Data
  TreeMenu: EditorTreeMenu,
  DataTable: EditorDataTable,
  // Pattern authoring
  Slot: EditorSlot,
  // Shared project layout
  Outlet: EditorOutlet,
};
