export const SAVE_KEY = 'a1-wrenchworks-save-v1'
export const SAVE_VERSION = 1
export const OFFLINE_LIMIT_SECONDS = 12 * 60 * 60
export const MAX_SERVICE_LEVEL = 25

export const BUSINESSES = [
  {
    id: 'oil-stand',
    name: 'Driveway oil stand',
    shortName: 'Oil stand',
    district: 'Home block',
    description: 'Fresh filters, clean oil and one borrowed floor jack.',
    jobName: 'Oil change',
    actionLabel: 'Change oil',
    icon: 'oil_barrel',
    tone: 'highlighted',
    vehicle: 'compact',
    unlockCost: 0,
    reputationRequired: 0,
    baseRevenue: 24,
    duration: 5,
    baseReputation: 1,
    upgradeBase: 90,
    hireBase: 240,
    managerBase: 2400,
  },
  {
    id: 'tire-bay',
    name: 'Corner tire bay',
    shortName: 'Tire bay',
    district: 'Market street',
    description: 'A proper lift, a tire machine and a growing stack of rubber.',
    jobName: 'Tire service',
    actionLabel: 'Mount tires',
    icon: 'tire_repair',
    tone: 'info',
    vehicle: 'wagon',
    unlockCost: 1800,
    reputationRequired: 30,
    baseRevenue: 115,
    duration: 12,
    baseReputation: 3,
    upgradeBase: 1800,
    hireBase: 4200,
    managerBase: 28000,
  },
  {
    id: 'brake-garage',
    name: 'Neighborhood brake garage',
    shortName: 'Brake garage',
    district: 'Old town',
    description: 'Two bays, honest inspections and the best coffee on the block.',
    jobName: 'Brake repair',
    actionLabel: 'Repair brakes',
    icon: 'car_repair',
    tone: 'error',
    vehicle: 'sedan',
    unlockCost: 24000,
    reputationRequired: 120,
    baseRevenue: 750,
    duration: 30,
    baseReputation: 8,
    upgradeBase: 15000,
    hireBase: 38000,
    managerBase: 260000,
  },
  {
    id: 'detail-studio',
    name: 'Downtown detail studio',
    shortName: 'Detail studio',
    district: 'Arts district',
    description: 'Paint correction, spotless cabins and a showroom shine.',
    jobName: 'Full detail',
    actionLabel: 'Detail a car',
    icon: 'auto_awesome',
    tone: 'accent',
    vehicle: 'coupe',
    unlockCost: 300000,
    reputationRequired: 400,
    baseRevenue: 6500,
    duration: 60,
    baseReputation: 20,
    upgradeBase: 180000,
    hireBase: 420000,
    managerBase: 3200000,
  },
  {
    id: 'engine-lab',
    name: 'Performance engine lab',
    shortName: 'Engine lab',
    district: 'Warehouse row',
    description: 'Diagnostics, rebuilds and careful tuning for serious machines.',
    jobName: 'Engine rebuild',
    actionLabel: 'Tune an engine',
    icon: 'precision_manufacturing',
    tone: 'warn',
    vehicle: 'muscle',
    unlockCost: 4000000,
    reputationRequired: 1200,
    baseRevenue: 90000,
    duration: 180,
    baseReputation: 65,
    upgradeBase: 2200000,
    hireBase: 5500000,
    managerBase: 42000000,
  },
  {
    id: 'collision-center',
    name: 'Metro collision center',
    shortName: 'Collision center',
    district: 'Industrial park',
    description: 'Frame racks, a paint booth and a team that makes damage disappear.',
    jobName: 'Collision restoration',
    actionLabel: 'Restore a car',
    icon: 'build',
    tone: 'success',
    vehicle: 'suv',
    unlockCost: 75000000,
    reputationRequired: 3500,
    baseRevenue: 2000000,
    duration: 480,
    baseReputation: 180,
    upgradeBase: 48000000,
    hireBase: 120000000,
    managerBase: 900000000,
  },
  {
    id: 'used-lot',
    name: 'Wrenchworks used cars',
    shortName: 'Used car lot',
    district: 'Motor mile',
    description: 'Carefully reconditioned cars, fair deals and keys changing hands.',
    jobName: 'Used car sale',
    actionLabel: 'Close a sale',
    icon: 'key',
    tone: 'highlighted',
    vehicle: 'classic',
    unlockCost: 1500000000,
    reputationRequired: 9000,
    baseRevenue: 55000000,
    duration: 900,
    baseReputation: 500,
    upgradeBase: 900000000,
    hireBase: 2400000000,
    managerBase: 18000000000,
  },
  {
    id: 'dealership',
    name: 'Wrenchworks new car dealership',
    shortName: 'Dealership',
    district: 'Commerce loop',
    description: 'A bright showroom, a busy service lane and brand-new inventory.',
    jobName: 'New car delivery',
    actionLabel: 'Deliver a car',
    icon: 'directions_car',
    tone: 'info',
    vehicle: 'sport',
    unlockCost: 50000000000,
    reputationRequired: 20000,
    baseRevenue: 2500000000,
    duration: 1800,
    baseReputation: 1400,
    upgradeBase: 32000000000,
    hireBase: 85000000000,
    managerBase: 650000000000,
  },
  {
    id: 'auto-mall',
    name: 'Regional auto mall',
    shortName: 'Auto mall',
    district: 'Beltway',
    description: 'Several brands, hundreds of cars and a service campus of your own.',
    jobName: 'Fleet delivery',
    actionLabel: 'Deliver a fleet',
    icon: 'domain',
    tone: 'accent',
    vehicle: 'executive',
    unlockCost: 2500000000000,
    reputationRequired: 45000,
    baseRevenue: 180000000000,
    duration: 3600,
    baseReputation: 4000,
    upgradeBase: 1800000000000,
    hireBase: 4200000000000,
    managerBase: 35000000000000,
  },
  {
    id: 'national-network',
    name: 'National Wrenchworks network',
    shortName: 'National network',
    district: 'Everywhere',
    description: 'A coast-to-coast company built one honest repair at a time.',
    jobName: 'Network expansion',
    actionLabel: 'Open a market',
    icon: 'public',
    tone: 'success',
    vehicle: 'supercar',
    unlockCost: 250000000000000,
    reputationRequired: 100000,
    baseRevenue: 25000000000000,
    duration: 7200,
    baseReputation: 12000,
    upgradeBase: 160000000000000,
    hireBase: 380000000000000,
    managerBase: 3000000000000000,
  },
]

export const DECISIONS = [
  {
    id: 'first-regular',
    requiredLifetime: 1000,
    title: 'Your first regular',
    prompt: 'A neighbor brings in a beloved old hatchback. What becomes your calling card?',
    choices: [
      {
        id: 'honest',
        label: 'Give the honest estimate',
        description: 'Reputation arrives 25% faster.',
        icon: 'handshake',
        effect: { reputation: 0.25 },
      },
      {
        id: 'premium',
        label: 'Use premium parts',
        description: 'Every job earns 18% more.',
        icon: 'workspace_premium',
        effect: { revenue: 0.18 },
      },
      {
        id: 'fast',
        label: 'Finish before lunch',
        description: 'Every crew works 15% faster.',
        icon: 'speed',
        effect: { speed: 0.15 },
      },
    ],
  },
  {
    id: 'fleet-offer',
    requiredLifetime: 50000,
    title: 'The delivery fleet',
    prompt: 'A local bakery needs dependable service for every van. How do you win the work?',
    choices: [
      {
        id: 'retainer',
        label: 'Offer a service plan',
        description: 'Every job earns 20% more.',
        icon: 'assignment',
        effect: { revenue: 0.2 },
      },
      {
        id: 'pit-crew',
        label: 'Build a pit crew',
        description: 'Every crew works 18% faster.',
        icon: 'groups',
        effect: { speed: 0.18 },
      },
      {
        id: 'community',
        label: 'Sponsor their route',
        description: 'Reputation arrives 30% faster.',
        icon: 'volunteer_activism',
        effect: { reputation: 0.3 },
      },
    ],
  },
  {
    id: 'shop-identity',
    requiredLifetime: 1000000,
    title: 'A name worth painting',
    prompt: 'The new sign is ready. What promise sits under the Wrenchworks name?',
    choices: [
      {
        id: 'craft',
        label: 'Built right',
        description: 'Hands-on jobs earn 75% more.',
        icon: 'construction',
        effect: { manual: 0.75 },
      },
      {
        id: 'care',
        label: 'People first',
        description: 'Reputation arrives 35% faster.',
        icon: 'favorite',
        effect: { reputation: 0.35 },
      },
      {
        id: 'precision',
        label: 'Every second counts',
        description: 'Every crew works 20% faster.',
        icon: 'timer',
        effect: { speed: 0.2 },
      },
    ],
  },
  {
    id: 'investor',
    requiredLifetime: 25000000,
    title: 'An investor calls',
    prompt: 'They like your numbers but want to know where the next dollar goes.',
    choices: [
      {
        id: 'tools',
        label: 'Buy better tools',
        description: 'Every job earns 25% more.',
        icon: 'hardware',
        effect: { revenue: 0.25 },
      },
      {
        id: 'training',
        label: 'Train the crew',
        description: 'Every crew works 22% faster.',
        icon: 'school',
        effect: { speed: 0.22 },
      },
      {
        id: 'warranty',
        label: 'Back every repair',
        description: 'Reputation arrives 40% faster.',
        icon: 'verified',
        effect: { reputation: 0.4 },
      },
    ],
  },
  {
    id: 'first-lot',
    requiredLifetime: 500000000,
    title: 'Cars on the lot',
    prompt: 'Your first batch of used cars is ready. How will you sell them?',
    choices: [
      {
        id: 'recondition',
        label: 'Recondition everything',
        description: 'Every job earns 30% more.',
        icon: 'auto_fix_high',
        effect: { revenue: 0.3 },
      },
      {
        id: 'simple-price',
        label: 'Use one fair price',
        description: 'Reputation arrives 50% faster.',
        icon: 'sell',
        effect: { reputation: 0.5 },
      },
      {
        id: 'quick-turn',
        label: 'Keep inventory moving',
        description: 'Every crew works 25% faster.',
        icon: 'sync_alt',
        effect: { speed: 0.25 },
      },
    ],
  },
  {
    id: 'manufacturer',
    requiredLifetime: 10000000000,
    title: 'The manufacturer meeting',
    prompt: 'A major automaker offers you a new-car franchise. What do you negotiate?',
    choices: [
      {
        id: 'allocation',
        label: 'Secure rare inventory',
        description: 'Every job earns 35% more.',
        icon: 'local_shipping',
        effect: { revenue: 0.35 },
      },
      {
        id: 'service',
        label: 'Own the service lane',
        description: 'Every crew works 28% faster.',
        icon: 'home_repair_service',
        effect: { speed: 0.28 },
      },
      {
        id: 'academy',
        label: 'Open a technician academy',
        description: 'Hands-on jobs earn 100% more and reputation arrives 20% faster.',
        icon: 'engineering',
        effect: { manual: 1, reputation: 0.2 },
      },
    ],
  },
  {
    id: 'regional-brand',
    requiredLifetime: 250000000000,
    title: 'A regional brand',
    prompt: 'Wrenchworks is becoming a household name. What do you protect as you grow?',
    choices: [
      {
        id: 'quality-board',
        label: 'Create a quality board',
        description: 'Reputation arrives 60% faster.',
        icon: 'fact_check',
        effect: { reputation: 0.6 },
      },
      {
        id: 'buying-power',
        label: 'Use your buying power',
        description: 'Every job earns 40% more.',
        icon: 'savings',
        effect: { revenue: 0.4 },
      },
      {
        id: 'operations',
        label: 'Standardize operations',
        description: 'Every crew works 32% faster.',
        icon: 'account_tree',
        effect: { speed: 0.32 },
      },
    ],
  },
  {
    id: 'national-stage',
    requiredLifetime: 5000000000000,
    title: 'The national stage',
    prompt: 'You can build the largest auto business in the country. What leads the expansion?',
    choices: [
      {
        id: 'trust',
        label: 'Lead with trust',
        description: 'Reputation arrives 75% faster.',
        icon: 'shield',
        effect: { reputation: 0.75 },
      },
      {
        id: 'scale',
        label: 'Lead with scale',
        description: 'Every job earns 50% more.',
        icon: 'trending_up',
        effect: { revenue: 0.5 },
      },
      {
        id: 'systems',
        label: 'Lead with systems',
        description: 'Every crew works 38% faster.',
        icon: 'settings_suggest',
        effect: { speed: 0.38 },
      },
    ],
  },
]

export const MILESTONES = [
  {
    id: 'first-hundred',
    title: 'First greasy hundred',
    description: 'Earn $100 from honest work.',
    icon: 'payments',
    metric: 'lifetimeEarned',
    target: 100,
    reward: 150,
  },
  {
    id: 'known-block',
    title: 'Known on the block',
    description: 'Reach 25 reputation.',
    icon: 'thumb_up',
    metric: 'reputation',
    target: 25,
    reward: 600,
  },
  {
    id: 'small-crew',
    title: 'A real crew',
    description: 'Employ 4 technicians.',
    icon: 'groups',
    metric: 'staff',
    target: 4,
    reward: 4500,
  },
  {
    id: 'ten-upgrades',
    title: 'Better tools, better work',
    description: 'Buy 10 shop upgrades.',
    icon: 'upgrade',
    metric: 'upgrades',
    target: 10,
    reward: 18000,
  },
  {
    id: 'first-manager',
    title: 'Keys to the shop',
    description: 'Promote your first manager.',
    icon: 'badge',
    metric: 'managers',
    target: 1,
    reward: 85000,
  },
  {
    id: 'five-businesses',
    title: 'Across town',
    description: 'Open 5 businesses.',
    icon: 'location_city',
    metric: 'businesses',
    target: 5,
    reward: 2200000,
  },
  {
    id: 'hundred-million',
    title: 'Nine-figure garage',
    description: 'Earn $100 million across your career.',
    icon: 'analytics',
    metric: 'lifetimeEarned',
    target: 100000000,
    reward: 18000000,
  },
  {
    id: 'car-seller',
    title: 'Keys change hands',
    description: 'Open the used car lot.',
    icon: 'key',
    metric: 'businesses',
    target: 7,
    reward: 500000000,
  },
  {
    id: 'dealer-principal',
    title: 'Dealer principal',
    description: 'Open the new car dealership.',
    icon: 'directions_car',
    metric: 'businesses',
    target: 8,
    reward: 15000000000,
  },
  {
    id: 'deep-bench',
    title: 'Deep bench',
    description: 'Employ 30 technicians.',
    icon: 'diversity_3',
    metric: 'staff',
    target: 30,
    reward: 75000000000,
  },
  {
    id: 'franchise-founder',
    title: 'Franchise founder',
    description: 'Start a new Wrenchworks franchise.',
    icon: 'hub',
    metric: 'franchises',
    target: 1,
    reward: 500000000,
  },
  {
    id: 'national-name',
    title: 'A national name',
    description: 'Open the national Wrenchworks network.',
    icon: 'public',
    metric: 'businesses',
    target: 10,
    reward: 50000000000000,
  },
]

export const FRANCHISE_REQUIREMENTS = {
  businessCount: 8,
  runEarned: 100000000000,
}
