export const BLOG_POSTS = [
  {
    id: 'search-shortcuts-and-walkthroughs',
    slug: 'search-shortcuts-and-walkthroughs',
    title: 'Search, shortcuts, and walkthroughs',
    kicker: 'Release newsletter',
    date: 'Jun 29, 2026',
    version: 'Upcoming',
    image: '/blog/a1-global-search-open.png',
    imageAlt: 'The A1 global search overlay open on the home page.',
    description: 'How global search, keyboard shortcuts, and generated walkthrough videos make A1 easier to navigate and explain.',
    keywords: ['search', 'shortcut', 'walkthrough', 'video', 'newsletter', 'release'],
    subtitle: 'A newsletter-style look at the A1 release work that makes the app easier to navigate, explain, and demo.',
    sections: [
      {
        title: 'Why this release matters',
        body: 'A1 has grown into a product workspace, not just a component catalog. As the surface area expands, people need faster ways to find work, jump between tools, and understand what changed in each release. Global search and keyboard shortcuts make the app feel smaller. Walkthrough videos make new workflows easier to share.',
      },
      {
        title: 'What changed',
        body: 'Search now reaches across pages, foundations, component categories, components, projects, labels, rules, and backlog work. The first result is automatically selected, so a keyboard user can type a term and press Enter without moving focus. The same release adds a visible keyboard menu, shortcut labels, and a repeatable video pipeline for feature demos.',
        image: '/blog/a1-global-search-button.png',
        imageAlt: 'The A1 global search results showing Button as the selected match.',
      },
    ],
    video: '/blog/a1-global-search.mp4',
  },
  {
    id: 'governed-creation-015',
    slug: 'governed-creation-gets-sharper',
    title: 'Governed creation gets sharper',
    kicker: 'Release newsletter',
    date: 'Jun 25, 2026',
    version: '0.15.0',
    image: '/help/project-pages.png',
    imageAlt: 'A1 project pages in the editor workspace.',
    description: 'A look back at richer project data, custom icons, virtual teammates, and component proposal groundwork in A1 0.15.0.',
    keywords: ['release', '0.15.0', 'projects', 'data', 'icons', 'virtual team', 'components'],
    subtitle: 'A1 0.15.0 pushed the app further from component catalog toward governed product-building workspace.',
    sections: [
      {
        title: 'A more realistic project workspace',
        body: 'The release added the Northstar Motors vehicle sample and a wide Vehicles dataset, giving the editor a richer end-to-end exercise: inventory pages, detail pages, image galleries, specifications, and data-bound cards. That matters because the editor needs real-ish content pressure to reveal gaps in layout, binding, navigation, and preview behavior.',
      },
      {
        title: 'Custom icons and virtual teammates',
        body: 'Project-scoped custom icon fonts made symbols practical for individual workspaces, while the virtual team expanded into data, architecture, design, and release-note review. The theme across the release was the same: make creation easier, but keep it inside reviewable A1 rules.',
        image: '/help/image-library.png',
        imageAlt: 'The A1 image library used by project workspaces.',
      },
    ],
  },
  {
    id: 'navigation-and-system-map-014',
    slug: 'navigation-and-system-map',
    title: 'Navigation, foundations, and the system map',
    kicker: 'Release newsletter',
    date: 'Jun 24, 2026',
    version: '0.14.0',
    image: '/help/open-editor-projects.png',
    imageAlt: 'The editor projects menu in A1.',
    description: 'How the 0.14.0 release clarified the app structure, foundation stories, and the design system architecture.',
    keywords: ['release', '0.14.0', 'navigation', 'foundations', 'system map', 'themes'],
    subtitle: 'A1 0.14.0 was about making the system easier to understand before making it bigger.',
    sections: [
      {
        title: 'A clearer main menu',
        body: 'The old resource-heavy navigation became focused groups: Explore, Foundations, Components, and Editors. That change made room for the product workspace to grow without burying core destinations. It also gave the Information Architect teammate a more concrete IA model to audit.',
      },
      {
        title: 'Foundations became easier to reason about',
        body: 'The release added a System map foundation page and expanded color architecture documentation. Foundations stopped being only reference pages and started becoming a visual explanation of how tokens, themes, labels, rules, components, patterns, and projects fit together.',
        image: '/help/editor-canvas.png',
        imageAlt: 'An A1 editor canvas showing a composed page.',
      },
    ],
  },
  {
    id: 'patterns-and-backlog-loop',
    slug: 'patterns-and-backlog-loop',
    title: 'Patterns and the backlog loop',
    kicker: 'Release newsletter',
    date: 'Jun 20, 2026',
    version: '0.13.0',
    image: '/help/patterns.png',
    imageAlt: 'The A1 patterns page.',
    description: 'A release story about reusable patterns, backlog review, and the operating rhythm around design-system work.',
    keywords: ['release', 'patterns', 'backlog', 'review', 'workflow', 'virtual team'],
    subtitle: 'Earlier release work connected reusable UI patterns with the backlog loop that keeps the system honest.',
    sections: [
      {
        title: 'Patterns made reuse concrete',
        body: 'Patterns gave the editor a middle layer between raw components and full pages. They let teams capture repeatable compositions, keep important structure locked, and still edit the content that makes each instance useful.',
      },
      {
        title: 'Backlog review became part of the product',
        body: 'The backlog gained stronger board views, virtual review helpers, and status cleanup that reads the changelog. The result is a tighter loop: discover a product or system issue, file it, review it, ship it, and let release notes move the work forward.',
        image: '/help/backlog-board.png',
        imageAlt: 'The A1 backlog board with ticket columns.',
      },
    ],
  },
  {
    id: 'projects-patterns-and-editor-012',
    slug: 'projects-patterns-and-editor',
    title: 'Projects, patterns, and the editor mature',
    kicker: 'Release newsletter',
    date: 'Jun 22, 2026',
    version: '0.12.0',
    image: '/help/editor-canvas.png',
    imageAlt: 'The A1 editor canvas with page content selected.',
    description: 'The 0.12.0 release tightened the editor experience around projects, page composition, and reusable structure.',
    keywords: ['release', '0.12.0', 'editor', 'projects', 'patterns', 'canvas'],
    subtitle: 'A1 0.12.0 continued turning the editor into the center of everyday system work.',
    sections: [
      {
        title: 'The editor became more dependable',
        body: 'The release focused on the surfaces people touch while composing real pages: project navigation, reusable patterns, page structure, and canvas editing. It made the app feel less like a demo and more like a workspace where system decisions can be used repeatedly.',
      },
      {
        title: 'Reusable work moved closer to the canvas',
        body: 'Patterns and editor-side affordances made it easier to reuse good structure instead of rebuilding it from scratch. That direction set up later work around pattern locking, shared history, and governed creation.',
        image: '/help/patterns.png',
        imageAlt: 'The A1 patterns page showing reusable patterns.',
      },
    ],
  },
  {
    id: 'shared-workspace-foundation-011',
    slug: 'shared-workspace-foundation',
    title: 'The shared workspace foundation',
    kicker: 'Release newsletter',
    date: 'Jun 22, 2026',
    version: '0.11.0',
    image: '/help/open-editor-projects.png',
    imageAlt: 'The A1 editor menu opened from the top navigation.',
    description: 'A release about making A1 collaborative enough for real teams: accounts, shared state, images, and project persistence.',
    keywords: ['release', '0.11.0', 'shared workspace', 'accounts', 'sync', 'supabase'],
    subtitle: 'A1 0.11.0 was infrastructure-heavy, but it changed the product promise.',
    sections: [
      {
        title: 'From local workspace to shared system',
        body: 'The app moved toward signed-in, shared workspace behavior. Projects, patterns, themes, and images could be treated as common team assets rather than isolated browser state. That foundation is what later made shared labels, history, and backlog workflows make sense.',
      },
      {
        title: 'Collaboration became a product requirement',
        body: 'Presence, safe re-hydration, cloud sync, and account flows pointed A1 toward collaborative product work. The goal was not simply storage; it was making the design system usable by a team without losing the guardrails of the editor.',
        image: '/help/project-pages.png',
        imageAlt: 'A1 project pages listed in the editor workspace.',
      },
    ],
  },
  {
    id: 'help-and-backlog-010',
    slug: 'help-and-backlog',
    title: 'Help, screenshots, and the backlog arrive',
    kicker: 'Release newsletter',
    date: 'Jun 21, 2026',
    version: '0.10.0',
    image: '/help/backlog-board.png',
    imageAlt: 'The A1 backlog board with status columns.',
    description: 'The 0.10.0 release replaced static roadmap thinking with a real backlog and began tying help content to live screenshots.',
    keywords: ['release', '0.10.0', 'backlog', 'help', 'screenshots', 'roadmap'],
    subtitle: 'A1 0.10.0 made product feedback and product education part of the app itself.',
    sections: [
      {
        title: 'The backlog became real',
        body: 'The old roadmap page gave way to a ticket tracker with statuses, queues, voting, Q&A, notifications, and local sync. That made A1 work visible inside A1, instead of scattering product decisions across files and chats.',
      },
      {
        title: 'Help started using the product',
        body: 'The first Playwright-powered Help screenshots made documentation less abstract. Instead of describing a stale UI, Help could show captured app states and be refreshed as workflows changed.',
        image: '/help/open-editor-menu.png',
        imageAlt: 'A Help screenshot showing the editor menu.',
      },
    ],
  },
  {
    id: 'component-polish-009',
    slug: 'component-polish-and-editor-fit',
    title: 'Component polish and editor fit',
    kicker: 'Release newsletter',
    date: 'Jun 20, 2026',
    version: '0.9.0',
    image: '/help/editor-canvas.png',
    imageAlt: 'The A1 editor canvas and configuration panel.',
    description: 'A focused release on sticky actions, card behavior, header state, and making code examples easier to work with.',
    keywords: ['release', '0.9.0', 'card', 'top header', 'code', 'editor'],
    subtitle: 'A1 0.9.0 refined how component details behave inside real editor surfaces.',
    sections: [
      {
        title: 'Polish where composition gets tricky',
        body: 'Sticky actions were scoped to the canvas, card hero badges gained more flexibility, selected header state improved, and code blocks became less noisy. These are the kinds of changes that make the system feel quieter during repeated work.',
      },
      {
        title: 'Small component changes, larger product effect',
        body: 'Each fix was modest on its own, but together they reduced friction in the places users were already spending time: configuring components, reading generated code, and editing pages.',
      },
    ],
  },
  {
    id: 'collapsible-code-finish-0082',
    slug: 'collapsible-code-finish',
    title: 'Collapsible code gets finished',
    kicker: 'Release newsletter',
    date: 'Jun 19, 2026',
    version: '0.8.2',
    image: '/help/editor-canvas.png',
    imageAlt: 'The A1 editor canvas.',
    description: 'The 0.8.2 patch finished the Collapsible Code wiring in configurators and generated editor snippets.',
    keywords: ['release', '0.8.2', 'code', 'collapsible', 'editor'],
    subtitle: 'A small patch can matter when it makes dense implementation output easier to read.',
    sections: [
      {
        title: 'Less wall-of-code fatigue',
        body: 'The Code configurator gained Collapsible and Collapsed lines controls, and the editor read-only React snippet view adopted collapsible output. Big generated bundles became scannable instead of overwhelming.',
      },
      {
        title: 'Configurator parity matters',
        body: 'The release was small, but it kept the component configurator aligned with the design-system API. That keeps docs, examples, and editor behavior from drifting apart.',
      },
    ],
  },
  {
    id: 'home-and-theme-layout-0081',
    slug: 'home-and-theme-layout-tweaks',
    title: 'Home and theme layout tweaks',
    kicker: 'Release newsletter',
    date: 'Jun 19, 2026',
    version: '0.8.1',
    image: '/help/open-editor-projects.png',
    imageAlt: 'The A1 editor entry point.',
    description: 'The 0.8.1 patch cleaned up Home platform copy layout and the Themes list action alignment.',
    keywords: ['release', '0.8.1', 'home', 'themes', 'layout'],
    subtitle: 'A1 0.8.1 was a tiny visual cleanup release, the kind that makes a product feel more deliberate.',
    sections: [
      {
        title: 'Home read less forced',
        body: 'The Home Platforms section stopped forcing centered heading and body copy, which gave the content a calmer editorial rhythm.',
      },
      {
        title: 'Theme actions aligned with intent',
        body: 'The Themes list New theme action moved into a left-aligned ButtonContainer, matching the way people scan and act on workspace lists.',
      },
    ],
  },
  {
    id: 'ai-gating-and-grid-008',
    slug: 'ai-gating-and-grid-controls',
    title: 'AI gating and grid controls',
    kicker: 'Release newsletter',
    date: 'Jun 19, 2026',
    version: '0.8.0',
    image: '/help/image-library.png',
    imageAlt: 'The A1 image library.',
    description: 'The 0.8.x releases made AI optional by default, improved collapsible code, and added practical layout controls.',
    keywords: ['release', '0.8.0', '0.8.1', '0.8.2', 'ai', 'grid', 'code'],
    subtitle: 'A1 0.8.x balanced power with restraint: useful AI hooks, but no surprise API calls.',
    sections: [
      {
        title: 'AI became opt-in',
        body: 'AI entry points were hidden unless explicitly enabled, protecting users from accidental API usage. That decision shaped later local-first AI work: powerful when requested, quiet when not.',
      },
      {
        title: 'The editor gained better layout and code tools',
        body: 'Grid alignment controls, collapsible code blocks, and improved inline editable text made the editor more practical. The release also cleaned up smaller home and theme-list layout issues.',
      },
    ],
  },
  {
    id: 'shared-history-007',
    slug: 'shared-history',
    title: 'Shared history begins',
    kicker: 'Release newsletter',
    date: 'Jun 19, 2026',
    version: '0.7.0',
    image: '/help/project-pages.png',
    imageAlt: 'The A1 project pages workspace.',
    description: 'The 0.7.0 release introduced shared edit history with user attribution for pages and patterns.',
    keywords: ['release', '0.7.0', 'history', 'shared', 'collaboration', 'patterns'],
    subtitle: 'A1 0.7.0 made changes easier to trust because the app could show who changed what.',
    sections: [
      {
        title: 'History became shared context',
        body: 'Edit history moved beyond a local undo stack. Page and pattern edits could be logged with user attribution, restored, renamed, and reviewed by everyone in the shared workspace.',
      },
      {
        title: 'Trust is a product feature',
        body: 'For a governed design system, shared history is more than convenience. It lets a team understand how a page or pattern evolved, and it makes experimentation safer.',
      },
    ],
  },
  {
    id: 'presence-and-rehydrate-006',
    slug: 'presence-and-safe-rehydrate',
    title: 'Presence and safe re-hydration',
    kicker: 'Release newsletter',
    date: 'Jun 19, 2026',
    version: '0.6.0',
    image: '/help/editor-canvas.png',
    imageAlt: 'The A1 editor canvas.',
    description: 'The 0.6.0 release started the live collaboration story with editor presence and safer cloud updates.',
    keywords: ['release', '0.6.0', 'presence', 'collaboration', 'sync'],
    subtitle: 'A1 0.6.0 asked a simple collaboration question: can the editor update without clobbering active work?',
    sections: [
      {
        title: 'Presence made collaboration visible',
        body: 'The editor began showing who else was on the same page. That changed the workspace from an isolated editor into something closer to a shared room.',
      },
      {
        title: 'Safe updates mattered first',
        body: 'Cloud changes could be adopted automatically only when the local editor was not mid-edit. It was not full CRDT collaboration yet, but it established the rule that sync should never destroy active work.',
      },
    ],
  },
  {
    id: 'shared-cloud-workspace-005',
    slug: 'shared-cloud-workspace',
    title: 'The cloud workspace takes shape',
    kicker: 'Release newsletter',
    date: 'Jun 19, 2026',
    version: '0.5.0',
    image: '/help/open-editor-projects.png',
    imageAlt: 'The A1 editor projects menu.',
    description: 'The 0.5.0 release introduced accounts, Supabase-backed sync, shared workspace storage, analytics, and richer editor configuration.',
    keywords: ['release', '0.5.0', 'cloud sync', 'accounts', 'supabase', 'analytics'],
    subtitle: 'A1 0.5.0 was the moment the app stopped being only local.',
    sections: [
      {
        title: 'Accounts and shared data arrived',
        body: 'Optional Supabase configuration introduced account flows, cloud sync, shared workspace state, image storage, and an invite-only gate. The app still worked locally, but a live team workspace was now possible.',
      },
      {
        title: 'Editor details kept improving',
        body: 'The same release added project JSON views, paragraph weight controls, DefinitionList links, improved inline editing selection, and TODO filtering. It mixed infrastructure with practical day-to-day editor improvements.',
      },
    ],
  },
  {
    id: 'component-library-foundation-003',
    slug: 'component-library-foundation',
    title: 'The component library foundation',
    kicker: 'Release newsletter',
    date: 'Jun 17, 2026',
    version: '0.3.0',
    image: '/help/open-editor-menu.png',
    imageAlt: 'The A1 editor menu.',
    description: 'The 0.3.0 release expanded the app around component exploration, editor examples, and early design-system workflows.',
    keywords: ['release', '0.3.0', 'components', 'editor', 'design system'],
    subtitle: 'A1 0.3.0 gave the app more of its design-system shape.',
    sections: [
      {
        title: 'The system became explorable',
        body: 'Component and foundation work began forming a real app surface around the design system. Rather than being only package code, A1 started to present itself as something users could browse, configure, and learn from.',
      },
      {
        title: 'Editor examples connected code to product',
        body: 'Early editor examples helped prove that the component library could be used to author meaningful pages, not just isolated component demos.',
      },
    ],
  },
  {
    id: 'first-public-shape-002',
    slug: 'first-public-shape',
    title: 'The first public shape of A1 web',
    kicker: 'Release newsletter',
    date: 'Jun 15, 2026',
    version: '0.2.0',
    image: '/help/open-editor-projects.png',
    imageAlt: 'The A1 editor entry point.',
    description: 'The 0.2.0 release captured the first recognizable shape of the A1 web app: navigation, system pages, and editor direction.',
    keywords: ['release', '0.2.0', 'start', 'navigation', 'editor'],
    subtitle: 'A1 0.2.0 was where the app started to look like a product rather than a collection of experiments.',
    sections: [
      {
        title: 'A product shell emerged',
        body: 'The release established the early app shell and navigation needed for a design-system workspace. It gave the system somewhere to live and gave future features a predictable place to land.',
      },
      {
        title: 'The editor direction was already visible',
        body: 'Even early on, the center of gravity was clear: use A1 components and tokens to create structured pages, then keep those pages inside system rules.',
      },
    ],
  },
  {
    id: 'legacy-v013',
    slug: 'legacy-v013-release',
    title: 'Legacy release: the backlog loop hardens',
    kicker: 'Legacy release',
    date: 'Earlier cycle',
    version: 'v0.13.0',
    image: '/help/backlog-board.png',
    imageAlt: 'The A1 backlog board.',
    description: 'A legacy release cycle focused on backlog maturity, duplicate handling, and stronger virtual product-owner workflows.',
    keywords: ['legacy', 'v0.13.0', 'backlog', 'product owner', 'duplicates'],
    subtitle: 'The legacy v0.13.0 notes show A1 becoming more serious about product operations.',
    sections: [
      {
        title: 'Backlog quality improved',
        body: 'Duplicate detection, merge flows, and product-owner review made backlog work easier to maintain. The app began treating product operations as part of the system, not an external chore.',
      },
      {
        title: 'Agent handoff became clearer',
        body: 'Build-with-AI prompts converted tickets into implementation-ready context. It was a pragmatic shift away from trying to run autonomous work inside the app and toward giving coding agents better instructions.',
      },
    ],
  },
  {
    id: 'legacy-v0121',
    slug: 'legacy-v0121-release',
    title: 'Legacy release: help screenshots expand',
    kicker: 'Legacy release',
    date: 'Earlier cycle',
    version: 'v0.12.1',
    image: '/help/project-pages.png',
    imageAlt: 'A Help screenshot showing project pages.',
    description: 'A legacy patch release expanded Help screenshots across desktop and mobile workflows.',
    keywords: ['legacy', 'v0.12.1', 'help', 'screenshots', 'mobile'],
    subtitle: 'The v0.12.1 patch made Help more visual and less dependent on prose alone.',
    sections: [
      {
        title: 'Screenshots covered more workflows',
        body: 'Help captures expanded to Projects, the Editor menu, project pages, the canvas, Patterns, Image library, and Backlog. Desktop and mobile screenshots gave documentation better coverage across breakpoints.',
      },
      {
        title: 'Docs became refreshable',
        body: 'Because the screenshots came from Playwright, Help could be refreshed against the running app rather than maintained as static hand-made images.',
      },
    ],
  },
  {
    id: 'legacy-v011',
    slug: 'legacy-v011-release',
    title: 'Legacy release: virtual team foundations',
    kicker: 'Legacy release',
    date: 'Earlier cycle',
    version: 'v0.11.0',
    image: '/help/backlog-board.png',
    imageAlt: 'The A1 backlog board.',
    description: 'A legacy release about the first virtual product-owner loops and backlog review mechanics.',
    keywords: ['legacy', 'v0.11.0', 'virtual team', 'product owner', 'backlog'],
    subtitle: 'The v0.11.0 notes show the beginning of local virtual review inside A1.',
    sections: [
      {
        title: 'The product owner moved into the app',
        body: 'A deterministic virtual Product Owner could review backlog items, set priority and size, and ask value questions. It was local-only, but it established the persona pattern used by later virtual teammates.',
      },
      {
        title: 'Questions became structured',
        body: 'Persona questions could be answered inline with options, keeping clarification tied to the ticket rather than scattered elsewhere.',
      },
    ],
  },
  {
    id: 'legacy-v010',
    slug: 'legacy-v010-release',
    title: 'Legacy release: help and roadmap shift',
    kicker: 'Legacy release',
    date: 'Earlier cycle',
    version: 'v0.10.0',
    image: '/help/open-editor-menu.png',
    imageAlt: 'The editor menu captured for Help.',
    description: 'A legacy release that moved from roadmap markdown toward app-native help and backlog workflows.',
    keywords: ['legacy', 'v0.10.0', 'help', 'roadmap', 'backlog'],
    subtitle: 'The v0.10.0 release was a transition from static documentation toward live product surfaces.',
    sections: [
      {
        title: 'Roadmap thinking changed',
        body: 'The old roadmap page was removed in favor of a live backlog. That made prioritization and feedback part of the product instead of a separate markdown artifact.',
      },
      {
        title: 'Help gained its first captured visuals',
        body: 'The Help screenshot proof of concept began with editor entry points, pointing toward the richer visual docs that came later.',
      },
    ],
  },
  {
    id: 'legacy-v009',
    slug: 'legacy-v009-release',
    title: 'Legacy release: component refinements',
    kicker: 'Legacy release',
    date: 'Earlier cycle',
    version: 'v0.9.0',
    image: '/help/editor-canvas.png',
    imageAlt: 'The A1 editor canvas.',
    description: 'A legacy release focused on component behavior details that matter inside the editor.',
    keywords: ['legacy', 'v0.9.0', 'components', 'card', 'code', 'header'],
    subtitle: 'The v0.9.0 release cleaned up component details that become highly visible in a product workspace.',
    sections: [
      {
        title: 'Better behavior at composition time',
        body: 'Sticky actions, Card hero badges, selected TopHeader state, and collapsible Code all reduced friction in day-to-day page composition and documentation.',
      },
      {
        title: 'Small details compound',
        body: 'These refinements were not flashy, but they made the system more comfortable to use repeatedly.',
      },
    ],
  },
  {
    id: 'legacy-v008',
    slug: 'legacy-v008-release',
    title: 'Legacy release: AI gets a switch',
    kicker: 'Legacy release',
    date: 'Earlier cycle',
    version: 'v0.8.0',
    image: '/help/image-library.png',
    imageAlt: 'The A1 image library.',
    description: 'A legacy release that put AI features behind an explicit flag and improved editor ergonomics.',
    keywords: ['legacy', 'v0.8.0', 'ai', 'grid', 'code', 'inline editable'],
    subtitle: 'The v0.8.0 release set an important boundary: AI should be available, but not surprising.',
    sections: [
      {
        title: 'AI became deliberate',
        body: 'Every AI entry point was gated behind configuration, preventing accidental API usage. That principle still shows up in local-first and opt-in AI workflows throughout A1.',
      },
      {
        title: 'Editor controls kept improving',
        body: 'Collapsible code, Grid vertical alignment, and better editable marked text made the editor easier to use with real content.',
      },
    ],
  },
  {
    id: 'site-origin-story',
    slug: 'the-very-start-of-a1-web',
    title: 'The very start of A1 web',
    kicker: 'Origin story',
    date: 'Jun 8, 2026',
    version: '0.2.0',
    image: '/help/open-editor-projects.png',
    imageAlt: 'The A1 editor projects entry point.',
    description: 'How the site began: a place to prove that tokens, components, and page definitions could become a governed product workspace.',
    keywords: ['origin', 'start', 'site', '0.2.0', 'a1 web'],
    subtitle: 'Before A1 web had a backlog, walkthroughs, virtual teammates, or release newsletters, it needed one convincing idea.',
    sections: [
      {
        title: 'The first idea',
        body: 'The site started as a home for a design system, but the important bet was broader: the same tokens and components used for documentation could also build real product pages. That is why the editor, component registry, and foundations have always lived close together.',
      },
      {
        title: 'The shape was already there',
        body: 'Even in the earliest releases, A1 web was pointing toward a rules-based workspace: browse the system, compose with approved parts, keep work structured as JSON, and make every new feature easier to inspect and govern.',
        image: '/help/open-editor-menu.png',
        imageAlt: 'The early editor menu pattern in A1.',
      },
    ],
  },
]

export function getBlogPostBySlug(slug) {
  return BLOG_POSTS.find((post) => post.slug === slug) || null
}
