/**
 * Editor help — searchable, categorized documentation of every editor feature.
 *
 * ▶ To maintain: this page is driven entirely by the `HELP` array below. When an
 *   editor feature is added, changed, or removed, update the relevant article (or
 *   add/remove one). Each article has an `id`, `title`, `keywords` (used for
 *   search), and a `body` (JSX). Keep `keywords` generous so search finds it.
 */
import { useEffect, useMemo, useState } from 'react'
import {
  Accordion,
  Banner,
  Breadcrumb,
  Button,
  ButtonContainer,
  Code,
  DefinitionList,
  Figure,
  Grid,
  GridItem,
  Heading,
  Icon,
  Link,
  List,
  ListItem,
  MessageBadge,
  MessageEmptyState,
  PageNav,
  Paragraph,
  Section,
  Stack,
  TextField,
} from '@gtivr4/a1-design-system-react'
import { MOD, ALT, SHIFT, DEL } from '../editor/shortcuts.ts'

// Small helpers for article bodies ------------------------------------------------

const P = (props) => <Paragraph size="sm" {...props} />
const Steps = ({ items }) => (
  <List as="ol" variant="ordered" size="sm">
    {items.map((it, i) => <ListItem key={i}>{it}</ListItem>)}
  </List>
)
const Bullets = ({ items }) => (
  <List variant="unordered" size="sm">
    {items.map((it, i) => <ListItem key={i}>{it}</ListItem>)}
  </List>
)
const Kbd = ({ children }) => <Code variant="inline">{children}</Code>

// Track a mobile-sized viewport so each screenshot shows the device-appropriate capture.
function useIsMobile(query = '(max-width: 640px)') {
  const [isMobile, setIsMobile] = useState(
    () => typeof window !== 'undefined' && !!window.matchMedia?.(query).matches,
  )
  useEffect(() => {
    if (typeof window === 'undefined' || !window.matchMedia) return undefined
    const mql = window.matchMedia(query)
    const onChange = () => setIsMobile(mql.matches)
    onChange()
    mql.addEventListener('change', onChange)
    return () => mql.removeEventListener('change', onChange)
  }, [query])
  return isMobile
}

// A captioned walkthrough screenshot. Pass the base `name`; the device-appropriate
// capture is shown (`<name>.png` on desktop, `<name>-mobile.png` on mobile). Images are
// auto-generated by scripts/help-screenshots.mjs into public/help/ — re-run to refresh.
function Shot({ name, alt, caption }) {
  const isMobile = useIsMobile()
  return <Figure src={`/help/${name}${isMobile ? '-mobile' : ''}.png`} alt={alt} caption={caption} radius="md" />
}

// ── Content ────────────────────────────────────────────────────────────────────

const HELP = [
  {
    id: 'overview',
    title: 'Getting started',
    icon: 'rocket_launch',
    articles: [
      {
        id: 'what-is-editor',
        title: 'What the editor is',
        keywords: 'overview intro json page builder projects pages components prototype what is',
        body: (
          <Stack gap="sm">
            <P>
              The editor is a layout-first page builder. You arrange real A1 components on a
              canvas, configure their properties, and the result is stored as a JSON page
              definition — the same format that drives the live prototype and future site builder.
            </P>
            <P>The structure is three levels:</P>
            <Bullets items={[
              <><strong>Projects</strong> — an isolated set of pages with its own navigation.</>,
              <><strong>Pages</strong> — each page is one screen, arranged in a hierarchy.</>,
              <><strong>Components</strong> — the elements on each page (Sections, Stacks, Headings, Buttons…).</>,
            ]} />
          </Stack>
        ),
      },
      {
        id: 'open-editor',
        title: 'Opening the editor',
        keywords: 'open editor projects home start navigate top nav screenshot walkthrough',
        body: (
          <Stack gap="sm">
            <P>Open <strong>Editor</strong> from the top navigation. You land on the <strong>Projects</strong> list — your home base. From there, open a project to edit its pages, or create a new one.</P>
            <Shot
              name="open-editor-projects"
              alt="The editor Projects list: the top navigation with Editor selected, a Projects heading, New project and Image library buttons, and cards for the A1 Showcase and Ember & Oak sample projects."
              caption="The Projects list — your home base, with the bundled sample projects and a New project button."
            />
            <P>The top-nav <strong>Editor</strong> menu also lists every project for a one-click jump straight into it.</P>
            <Shot
              name="open-editor-menu"
              alt="The top-navigation Editor menu open, showing Projects, Patterns, Image library, Theme, and Rules. The Projects item expands to a one-click list of every project."
              caption="The top-nav Editor menu — Projects expands to every project for a one-click jump."
            />
          </Stack>
        ),
      },
    ],
  },

  {
    id: 'projects',
    title: 'Projects',
    icon: 'folder',
    articles: [
      {
        id: 'create-project',
        title: 'Creating a project',
        keywords: 'create new project name description icon dialog add',
        body: (
          <Stack gap="sm">
            <P>On the Projects list, choose <strong>New project</strong>. Give it a name, an optional description, and an icon. The project opens to its page overview, ready for its first page.</P>
          </Stack>
        ),
      },
      {
        id: 'manage-projects',
        title: 'Opening, renaming, duplicating & deleting projects',
        keywords: 'open rename duplicate delete project card right click context menu manage kebab',
        body: (
          <Stack gap="sm">
            <P>Each project is a card showing its icon, description, page count, and last-updated date.</P>
            <Bullets items={[
              <><strong>Open</strong> — click the card’s Open button (or right-click → Open).</>,
              <><strong>Rename / Duplicate / Delete</strong> — right-click a card for the options menu. Delete asks for confirmation and removes the project and its pages.</>,
            ]} />
            <Shot
              name="open-editor-projects"
              alt="The Projects list with each project shown as a card — icon, description, page count, and last-updated date."
              caption="Each project is a card on the Projects list — right-click one for rename, duplicate, or delete."
            />
            <P>The <Link href="/editor?project=proj-ember-oak" onClick={(e) => e.preventDefault()}>Ember &amp; Oak</Link> sample project is bundled as a complete worked example — explore it to see the features in context.</P>
          </Stack>
        ),
      },
      {
        id: 'project-isolation',
        title: 'Projects are isolated',
        keywords: 'isolation isolated separate scope links page link selector cross project',
        body: <P>A project’s pages, navigation, and in-page links only ever reference pages <em>within the same project</em>. When you link a Button or Link to a page, only that project’s pages appear in the selector.</P>,
      },
    ],
  },

  {
    id: 'pages',
    title: 'Pages & navigation',
    icon: 'description',
    articles: [
      {
        id: 'page-tree',
        title: 'The page tree (Pages tab)',
        keywords: 'page tree sidebar pages tab add edit duplicate delete page right click context menu',
        body: (
          <Stack gap="sm">
            <P>Inside a project, the sidebar’s <strong>Pages</strong> tab lists every page. Right-click a page (or use <strong>Add page</strong> in the footer) to:</P>
            <Bullets items={[
              <><strong>Add subpage</strong> / <strong>Add page below</strong></>,
              <><strong>Edit</strong> — selects the page so you can change its metadata</>,
              <><strong>Duplicate</strong> — copies the page and its content</>,
              <><strong>Delete</strong> — with confirmation (also removes any subpages)</>,
            ]} />
            <P>Click a page to open it in the editor. The other sidebar tab, <strong>Layers</strong>, shows the component tree of the open page.</P>
            <Shot
              name="project-pages"
              alt="A project open in the editor: the Pages tree in the left sidebar (Home, Menus, Reservations, About, Contact) and every page shown as a card in the main area with its level badge."
              caption="A project open — the Pages tree (left) and each page as a card, with L1/L2 level badges."
            />
          </Stack>
        ),
      },
      {
        id: 'page-hierarchy',
        title: 'Hierarchy & page levels (1–3)',
        keywords: 'hierarchy level depth nest drag drop reparent parent child 1 2 3 reorder',
        body: (
          <Stack gap="sm">
            <P><strong>Drag and drop</strong> pages in the tree to nest them. A page’s <strong>level</strong> is its depth in the tree (1 = top level), capped at 3 — the hierarchy is the source of truth.</P>
            <P>You can also set the level directly: select a page and change <strong>Level</strong> in its metadata; it re-parents to match. Levels that aren’t reachable from a page’s position are disabled.</P>
          </Stack>
        ),
      },
      {
        id: 'page-metadata',
        title: 'Page metadata: title, icon, description, level',
        keywords: 'page metadata title icon description level edit settings name',
        body: <P>With a page open and nothing selected on the canvas, the <strong>Configure</strong> panel shows the page settings: <strong>title</strong>, <strong>icon</strong>, <strong>description</strong>, and <strong>level</strong>. These drive the page’s entry in the auto-generated navigation.</P>,
      },
      {
        id: 'auto-nav',
        title: 'Auto-generated TopHeader',
        keywords: 'auto navigation topheader top header menu dropdown level 2 3 generated nav',
        body: (
          <Stack gap="sm">
            <P>A <strong>TopHeader</strong> is generated automatically from the page hierarchy and rendered above every page — in the edit canvas, preview, and the launched prototype.</P>
            <Bullets items={[
              'Level-1 pages become top-level nav items.',
              'Level-2 pages appear in a dropdown under their parent.',
              'Level-3 pages nest one level deeper in the menu.',
            ]} />
            <P>It updates live as you rename pages, change icons, or re-nest the tree.</P>
          </Stack>
        ),
      },
      {
        id: 'all-pages',
        title: 'See all pages',
        keywords: 'all pages overview grid open breadcrumb edit delete project',
        body: <P>A project’s home view lists every page as a card (with its level), so you can browse and open any page. A breadcrumb (Home › Projects › Project) and project-level <strong>Edit</strong> / <strong>Delete</strong> actions sit at the top.</P>,
      },
      {
        id: 'linking',
        title: 'Linking buttons, links & cards to pages',
        keywords: 'link button page navigation prototype href page link selector connect screens card navigation card icon button',
        body: (
          <Stack gap="sm">
            <P>Select a <strong>Button</strong>, <strong>Link</strong>, <strong>Icon Button</strong>, or a <strong>navigation Card</strong> (a Card with <strong>Variant: Navigation</strong>) and use the <strong>Link to page</strong> selector to point it at any page in the project. In the prototype, clicking it navigates there.</P>
            <P>Behind the scenes this stores an <Kbd>{'/?page=<id>'}</Kbd> href that the prototype resolves.</P>
          </Stack>
        ),
      },
    ],
  },

  {
    id: 'editing',
    title: 'Selecting & editing',
    icon: 'edit',
    articles: [
      {
        id: 'select',
        title: 'Selecting elements',
        keywords: 'select click element innermost canvas layers tree highlight selection',
        body: (
          <Stack gap="sm">
            <P>Click any element on the canvas to select it — the innermost element under the cursor wins. The matching node highlights in the <strong>Layers</strong> tree, and vice-versa.</P>
            <P>Selecting nothing (clicking empty space) shows the page settings in the Configure panel.</P>
            <Shot
              name="editor-canvas"
              alt="The editor with a page open: the Layers tree on the left, the page rendered on the canvas in the centre with the Edit / Preview / Code snippet toolbar above it, and the Configure panel on the right."
              caption="The editor canvas — Layers tree (left), the live canvas (centre), and the Configure panel (right)."
            />
          </Stack>
        ),
      },
      {
        id: 'edit-text',
        title: 'Editing text inline',
        keywords: 'text inline edit heading paragraph button label type content markdown',
        body: (
          <Stack gap="sm">
            <P>Click a heading, paragraph, or button label and type to edit it in place. Paragraphs support inline markdown — <Kbd>**bold**</Kbd>, <Kbd>*italic*</Kbd>, <Kbd>~~strike~~</Kbd>, <Kbd>==mark==</Kbd>, and <Kbd>`code`</Kbd>.</P>
            <P>Rich headings (with highlight/underline marks) and complex content are edited from the Configure panel instead.</P>
          </Stack>
        ),
      },
      {
        id: 'configure',
        title: 'The Configure (properties) panel',
        keywords: 'configure properties panel props variant size color padding gap edit settings aside',
        body: <P>The right-hand <strong>Configure</strong> tab shows controls for the selected component — variant, size, color, spacing, surface, and everything else that component supports. Changes apply to the canvas immediately and are written back into the page JSON.</P>,
      },
    ],
  },

  {
    id: 'components',
    title: 'Adding & arranging components',
    icon: 'widgets',
    articles: [
      {
        id: 'add',
        title: 'Adding components',
        keywords: 'add component catalog plus button drag drop insert new element',
        body: (
          <Stack gap="sm">
            <P>Add components in a few ways:</P>
            <Bullets items={[
              <>The <strong>Add</strong> tab in the right panel — pick from the catalog; it inserts at the current target.</>,
              <>The <strong>+ Add component</strong> button in the Layers footer, or a container’s <strong>+</strong> on the canvas.</>,
              <>Right-click an element → <strong>Add inside</strong> / <strong>Add below</strong>.</>,
              <>Drag a component from the Add panel onto the canvas.</>,
            ]} />
          </Stack>
        ),
      },
      {
        id: 'arrange',
        title: 'Moving, reordering & grouping',
        keywords: 'move reorder drag tree alt arrow up down group stack ungroup nest arrange',
        body: (
          <Stack gap="sm">
            <Bullets items={[
              <><strong>Reorder / re-nest</strong> — drag elements in the Layers tree.</>,
              <><strong>Move up / down</strong> — <Kbd>{`${ALT}↑`}</Kbd> / <Kbd>{`${ALT}↓`}</Kbd> among siblings.</>,
              <><strong>Group as Stack</strong> — <Kbd>{`${MOD}G`}</Kbd> wraps the selection in a Stack.</>,
              <><strong>Ungroup</strong> — <Kbd>{`${MOD}${SHIFT}G`}</Kbd> promotes a container’s children into its parent.</>,
            ]} />
          </Stack>
        ),
      },
      {
        id: 'duplicate-delete-convert',
        title: 'Duplicate, delete & convert',
        keywords: 'duplicate delete convert change type remove copy element context menu',
        body: (
          <Stack gap="sm">
            <Bullets items={[
              <><strong>Duplicate</strong> — <Kbd>{`${MOD}D`}</Kbd> or the context menu.</>,
              <><strong>Delete</strong> — <Kbd>{DEL}</Kbd> (an undo snackbar appears).</>,
              <><strong>Convert to</strong> — the context menu offers compatible types to switch a component into (e.g. Heading → Paragraph), carrying over what props match.</>,
            ]} />
            <P>Both the <strong>canvas right-click menu</strong> and the <strong>Layers tree menu</strong> offer these actions.</P>
          </Stack>
        ),
      },
    ],
  },

  {
    id: 'reuse',
    title: 'Reuse & restyling',
    icon: 'auto_fix_high',
    articles: [
      {
        id: 'copy-pattern',
        title: 'Copy pattern (restyle by style transfer)',
        keywords: 'copy pattern paste style restyle properties transfer cmd opt alt c v subtree match defaults',
        body: (
          <Stack gap="sm">
            <P>Copy the <strong>look</strong> of one element and apply it to others — a fast way to restyle many items.</P>
            <Steps items={[
              <>Select an element and press <Kbd>{`${MOD}${ALT}C`}</Kbd> (or right-click → <strong>Copy pattern</strong>).</>,
              <>Select another element and press <Kbd>{`${MOD}${ALT}V`}</Kbd> (or right-click → <strong>Paste pattern</strong>).</>,
            ]} />
            <Bullets items={[
              'Only visual props travel (variant, size, color, padding, gap, surface, gradient, radius, align…). Content, links, data, and state are left alone.',
              'It captures the whole subtree: paste a styled Card and its heading/paragraph/button styles transfer to another Card’s children too — every matching element by type.',
              'It captures each element’s effective style, including defaults, so the target ends up looking exactly like the source (not a partial blend).',
              'If nothing matches, a snackbar explains why.',
            ]} />
            <Banner status="info" variant="inline" title="Why ⌥ and not ⇧">
              The shortcuts use Option/Alt because the browser reserves ⌘⇧C for “Inspect Element”.
            </Banner>
          </Stack>
        ),
      },
      {
        id: 'versions',
        title: 'Versions',
        keywords: 'versions variants switch create rename delete a b compare branch alternatives',
        body: (
          <Stack gap="sm">
            <P>The <strong>Versions</strong> tab keeps named variants of a page side by side — useful for A/B exploration. Create a version, switch between them, and rename or delete them. Each version has its own working state.</P>
          </Stack>
        ),
      },
      {
        id: 'history',
        title: 'History, undo & redo',
        keywords: 'history undo redo jump restore rename timeline steps revert',
        body: (
          <Stack gap="sm">
            <P>Every change is a history step. Use <Kbd>{`${MOD}Z`}</Kbd> / <Kbd>{`${MOD}${SHIFT}Z`}</Kbd> to undo and redo, or the <strong>History</strong> tab to jump to, restore, or rename any step. History persists per page.</P>
          </Stack>
        ),
      },
    ],
  },

  {
    id: 'patterns',
    title: 'Patterns',
    icon: 'dashboard_customize',
    articles: [
      {
        id: 'what-is-pattern',
        title: 'What patterns are',
        keywords: 'pattern reusable composition template governed locked instance linked component group library vs copy pattern',
        body: (
          <Stack gap="sm">
            <P>A <strong>pattern</strong> is a reusable, governed composition — a saved group of components (a header, a card, a callout) that you insert into pages as <strong>linked instances</strong>. Edit the pattern once and every instance updates.</P>
            <P>That’s different from <strong>Copy pattern</strong> (in Reuse &amp; restyling), which is a one-time <em>style</em> transfer with no ongoing link. Patterns keep a live link and can lock parts so they stay consistent everywhere they’re used.</P>
          </Stack>
        ),
      },
      {
        id: 'create-pattern',
        title: 'Creating a pattern',
        keywords: 'create pattern new from selection right click duplicate patterns page workspace author',
        body: (
          <Stack gap="sm">
            <P>Three ways to make one:</P>
            <Bullets items={[
              <><strong>From a selection</strong> — select an element (and its children) on the canvas, right-click → <strong>Create pattern from selection</strong>. The selection becomes a new pattern and the element on the page becomes a linked instance of it.</>,
              <><strong>From scratch</strong> — open <strong>Patterns</strong> in the Editor menu and choose <strong>New pattern</strong> to author one on a blank canvas.</>,
              <><strong>Duplicate</strong> — right-click a pattern on the Patterns page → <strong>Duplicate</strong>.</>,
            ]} />
            <Shot
              name="patterns"
              alt="The Patterns page: a New pattern button and a grid of pattern cards, each showing its name, category, locked/editable summary, and project scope."
              caption="The Patterns page — author from scratch with New pattern, or open any pattern card to edit it."
            />
          </Stack>
        ),
      },
      {
        id: 'use-pattern',
        title: 'Using & detaching patterns',
        keywords: 'use insert pattern add panel drag instance update linked detach unlink loose nodes',
        body: (
          <Stack gap="sm">
            <P>With a page open, the <strong>Add</strong> tab’s <strong>Patterns</strong> section lists the patterns available to the project — click or drag one onto the canvas to insert an instance.</P>
            <Bullets items={[
              'Editing the pattern updates every instance automatically.',
              <>To break the link on one instance, right-click it → <strong>Detach pattern</strong>; it becomes ordinary, fully-editable nodes.</>,
            ]} />
          </Stack>
        ),
      },
      {
        id: 'pattern-governance',
        title: 'Locking, slots & scope',
        keywords: 'lock locked node content props read only governance slot fill area scope project specific all projects',
        body: (
          <Stack gap="sm">
            <P>When you author a pattern you decide what instances can change:</P>
            <Bullets items={[
              <><strong>Lock a component</strong> so it can’t be moved, deleted, or converted in instances.</>,
              <><strong>Lock content</strong> so its text is fixed.</>,
              <><strong>Lock individual properties</strong> (the lock icon next to a control) so they’re read-only in instances.</>,
            ]} />
            <P>Locked parts appear disabled in an instance’s Configure panel and re-sync to the pattern’s values whenever the pattern changes. Add a <strong>Slot</strong> to a pattern to leave a labelled fill-in area where instance users can add their own (optionally restricted) content.</P>
            <P>On the Patterns page, each pattern’s <strong>scope</strong> shows whether it’s available to all projects or limited to specific ones.</P>
          </Stack>
        ),
      },
    ],
  },

  {
    id: 'data-sources',
    title: 'Data sources',
    icon: 'table_chart',
    articles: [
      {
        id: 'what-are-data-sources',
        title: 'What data sources are',
        keywords: 'data source dataset table rows columns datagrid grid spreadsheet store scope project import json users sample',
        body: (
          <Stack gap="sm">
            <P>
              A <strong>data source</strong> is a reusable dataset — a named table of rows and
              columns you can edit, scope to projects, and (in future) bind into pages. Open it
              from the editor menu’s <Icon name="table_chart" size="sm" /> <strong>Data sources</strong> entry.
            </P>
            <Bullets items={[
              <>Each dataset is edited in a spreadsheet-style <strong>grid</strong> — double-click a cell to change its value.</>,
              <>Datasets are <strong>stored</strong> in your account when you’re signed in (shared workspace), or in this browser otherwise.</>,
              <>A built-in <strong>Users</strong> sample (fake people with contact details) is added on first use so there’s something to try.</>,
            ]} />
          </Stack>
        ),
      },
      {
        id: 'edit-scope-import-data',
        title: 'Editing, scoping & importing',
        keywords: 'edit cell add row column delete scope project global specific import json replace autosave datagrid',
        body: (
          <Stack gap="sm">
            <P>Open a dataset to edit it. Changes <strong>autosave</strong> as you work.</P>
            <Bullets items={[
              <><strong>Rows</strong> — double-click a cell to edit. <strong>Add row</strong> appends a row; tick rows and <strong>Delete</strong> to remove them.</>,
              <><strong>Columns</strong> — in the Columns card, rename a column, set its type, remove it, or <strong>Add column</strong>.</>,
              <><strong>Scope</strong> — leave a dataset available to <strong>all projects</strong> (the default), or turn on <strong>Limit to specific projects</strong> and pick which ones. (Some data, like users, is generic enough to stay global.)</>,
              <><strong>Import JSON</strong> — paste a JSON array of objects (keys become columns) or values; <strong>Replace from JSON</strong> swaps a dataset’s data the same way.</>,
            ]} />
            <P>
              Signed-in cloud storage needs the <Kbd>data_sources</Kbd> table created in Supabase
              (run the schema in <Kbd>apps/a1-web/supabase/schema.sql</Kbd>). Until then the page works
              locally in your browser.
            </P>
          </Stack>
        ),
      },
      {
        id: 'bind-data-into-pages',
        title: 'Binding data into a page',
        keywords: 'bind binding data token mustache curly braces dataset column value heading paragraph button prop dynamic editor data tab configure menu',
        body: (
          <Stack gap="sm">
            <P>
              A component’s text or a text prop can pull a value from a dataset. The easy way: select the
              element, then in the <strong>Configure</strong> panel use the <strong>Bind to data</strong>
              section — each bindable field (its Text, plus props like a link or image) has a menu of the
              project’s data sources and their fields. Pick one to bind it; <strong>Clear</strong> unbinds.
            </P>
            <P>
              Under the hood a binding is a token like <Kbd>{'{{ users.name }}'}</Kbd> — you can also type or
              paste one directly into any text:
            </P>
            <Bullets items={[
              <>The name before the dot is the dataset’s <strong>key</strong> — its name lowercased (e.g. “Users” → <Kbd>users</Kbd>).</>,
              <>The default is the <strong>first row</strong>; add an index for another: <Kbd>{'{{ users.name.2 }}'}</Kbd>.</>,
              <>Mix text and tokens — <Kbd>{'Hi {{ users.name }}'}</Kbd> — or bind a whole value on its own.</>,
              <>An unknown reference is shown as-is (e.g. <Kbd>{'{{ users.nope }}'}</Kbd>) so you can spot the typo.</>,
            ]} />
            <P>
              The editor’s <strong>Data</strong> tab (<Icon name="table_chart" size="sm" /> in the right panel)
              lists the project’s datasets and lets you <strong>click any token to copy it</strong>. Bound text
              shows the value read-only on the canvas — edit the binding from the Configure panel. Only data
              sources available to the page’s project (global or scoped to it) can be bound.
            </P>
          </Stack>
        ),
      },
      {
        id: 'repeat-over-data',
        title: 'Repeating an element for each row',
        keywords: 'repeat loop each row list cards auto build generate dataset data source rows record per row configure data',
        body: (
          <Stack gap="sm">
            <P>
              Turn one element into a list driven by a dataset. Select an element (often a
              <strong> Card</strong> or a <strong>Stack</strong>), then in the Configure panel’s
              <strong> Data</strong> section set <strong>Repeat for each row</strong> to a data source.
              It renders once per row.
            </P>
            <Bullets items={[
              <>Bindings inside use the <strong>current row</strong> — a card bound to <Kbd>{'{{ users.name }}'}</Kbd> and <Kbd>{'{{ users.email }}'}</Kbd> becomes one card per user.</>,
              <><strong>Show at most</strong> caps how many render (blank = all) — e.g. a “3 featured products” strip.</>,
              <><strong>Pick rows at random</strong> shows a random selection instead of the first few. It’s stable (it won’t reshuffle on every edit) and differs per element.</>,
              <>On the canvas the <strong>first copy is editable</strong> (it’s the template — editing it changes them all); the rest are read-only. <strong>Preview</strong> shows every row.</>,
              <>An explicit row index still wins inside a repeat (<Kbd>{'{{ users.name.0 }}'}</Kbd> always the first), which is handy for headers.</>,
              <>Set it back to <strong>Don’t repeat</strong> to stop.</>,
            ]} />
            <P>
              Put the repeating element inside a <strong>Grid</strong> or <strong>Stack</strong> to control how
              the rows lay out.
            </P>
          </Stack>
        ),
      },
      {
        id: 'fill-from-data',
        title: 'Filling items & options from data',
        keywords: 'fill collection items options definition list choice group select autocomplete fields distinct categories filter data driven array',
        body: (
          <Stack gap="sm">
            <P>
              Some components hold a list — a <strong>Definition List</strong>’s items, a <strong>Choice
              Group</strong> / <strong>Select</strong>’s options. Instead of typing them, generate the list from
              a dataset: select the component → Configure → <strong>Fill items/options from data</strong> → pick
              a data source and a mode.
            </P>
            <Bullets items={[
              <><strong>Each field of the item</strong> — a Definition List shows one <em>label / value</em> row per column of the current item. Great on a detail page to “show all details”.</>,
              <><strong>Distinct values of a column</strong> — one entry per unique value, so a Choice Group becomes a category filter that <strong>grows automatically</strong> as you add categories.</>,
              <><strong>Each row</strong> — one entry per row; map which column feeds each field (e.g. a Select of every product name).</>,
            ]} />
            <P>
              Row and distinct modes also take <strong>Show at most</strong> and <strong>Pick at random</strong>.
              This fills one component’s list — to repeat a whole element per row, use <strong>Repeat for each
              row</strong> instead.
            </P>
          </Stack>
        ),
      },
      {
        id: 'detail-pages',
        title: 'Detail pages (one page per item)',
        keywords: 'detail page item record link list grid template dynamic route slug id show details per item collection',
        body: (
          <Stack gap="sm">
            <P>
              Show the details of any item with a single <strong>detail page</strong> — not a page per record.
              The list links each item to the same page, which reads the item from the URL.
            </P>
            <Bullets items={[
              <><strong>Tag the page:</strong> with nothing selected, open <strong>Page settings</strong> → <strong>Shows details for</strong> and pick the dataset. Now every <Kbd>{'{{ dataset.field }}'}</Kbd> on the page resolves to one item.</>,
              <><strong>Design against a real item:</strong> pick a <strong>Preview item</strong> so the page shows actual data while you build it.</>,
              <><strong>Link from a list:</strong> on a page that repeats a Card over the dataset, set the card’s (or a button’s) link to the detail page. It automatically passes the current item, so each card opens its own details.</>,
              <><strong>Preview it:</strong> open Preview, click an item in the list, and the detail page shows that item. The address carries <Kbd>?item=…</Kbd>, so the link is shareable.</>,
            ]} />
            <P>
              Two pages — a list and a detail — cover a collection of any size. Each item is identified by a
              stable hidden id, so links keep working even when you rename or reorder rows.
            </P>
          </Stack>
        ),
      },
    ],
  },

  {
    id: 'media',
    title: 'Media & AI',
    icon: 'image',
    articles: [
      {
        id: 'figure',
        title: 'Figure: aspect ratio & crop',
        keywords: 'figure image aspect ratio 16:9 1:1 crop focal point object position cover',
        body: (
          <Stack gap="sm">
            <P>The Figure component can lock an image to a fixed <strong>aspect ratio</strong> (16:9 or 1:1), filling and cropping it to fit. The <strong>crop</strong> control sets the focal point on a 3×3 grid (center, top-left, …), so faces and subjects stay in frame.</P>
          </Stack>
        ),
      },
      {
        id: 'image-library',
        title: 'Image library',
        keywords: 'image library upload local images figure indexeddb store browser drag drop photo picker',
        body: (
          <Stack gap="sm">
            <P>The <strong>Image library</strong> (open it from the Editor menu or the <Icon name="photo_library" size="sm" /> button on the Projects home) holds images you upload, shared across every project.</P>
            <Shot
              name="image-library"
              alt="The Image library page with an upload area and the uploaded images, reusable across every project."
              caption="The Image library — upload once and reuse images across every project."
            />
            <Steps items={[
              'Upload images with the button or by dragging files onto the page; large images are downscaled automatically.',
              'In a Figure, click the photo_library button next to the Image URL to choose an image from the library (or upload one inline).',
              'Rename or delete images from the library page — deletes leave a missing image on any Figure that used them.',
            ]} />
            <Banner status="info" variant="inline" title="Where images live">
              When you’re signed in, images upload to the shared cloud workspace alongside your projects. Signed out (or with no backend configured), the library lives only in this browser (IndexedDB) and stays on this device.
            </Banner>
          </Stack>
        ),
      },
      {
        id: 'ai-images',
        title: 'AI image finder',
        keywords: 'ai image finder unsplash claude api key describe suggestions thumbnails caption generate',
        body: (
          <Stack gap="sm">
            <P>Next to a Figure’s <strong>Image URL</strong>, the <Icon name="auto_awesome" size="sm" /> button opens an AI image finder.</P>
            <Steps items={[
              'Describe the image you want.',
              'Claude returns three Unsplash thumbnails — select one, ask for three more, or re-prompt.',
              'Add an optional caption and apply it to the Figure.',
            ]} />
            <Banner status="warn" variant="inline" title="API key">
              You provide an Anthropic API key the first time; it’s stored only in this browser. Fine for local prototyping — don’t use this pattern in a public production build (proxy the call through a backend there).
            </Banner>
          </Stack>
        ),
      },
      {
        id: 'ai-icons',
        title: 'AI icon finder',
        keywords: 'ai icon finder material symbols describe suggest auto awesome configure icon button claude api key',
        body: (
          <Stack gap="sm">
            <P>Wherever a component has an <strong>Icon</strong> field in the Configure panel, the <Icon name="auto_awesome" size="sm" /> <strong>Find an icon with AI</strong> button beside it opens the AI icon finder.</P>
            <Steps items={[
              'Describe the icon you want — e.g. “download arrow” or “lock”.',
              'Claude returns three Material Symbols options; pick one, ask for three more, or re-prompt.',
            ]} />
            <P color="muted">Uses the same in-browser Anthropic API key as the other AI tools.</P>
          </Stack>
        ),
      },
      {
        id: 'ai-page-editor',
        title: 'AI page editor (chat)',
        keywords: 'ai page editor chat claude describe change whole page json generate modify instruction undo opus make with ai add page split button',
        body: (
          <Stack gap="sm">
            <P>The <strong>AI</strong> tab in the right-hand panel lets you edit the whole page by describing the change in plain language. Claude is sent the current page plus A1’s component and format reference, so it knows which components, props, and values are allowed.</P>
            <P>To start a brand-new page this way, open the <strong>Add page</strong> split button (the caret) in the Pages sidebar footer and choose <strong>Make with AI</strong> — it creates the page and drops you straight into the AI tab with the prompt focused.</P>
            <Steps items={[
              'Open the AI tab and type an instruction — e.g. “Add a hero section with a heading and a primary call-to-action”, or “Turn the three cards into a grid”.',
              'Press Enter (Shift+Enter for a new line). Claude returns a short summary and the updated page.',
              'The change is applied to the canvas automatically as a single step — press Cmd/Ctrl+Z to undo the whole edit.',
            ]} />
            <P>It’s conversational — follow-ups like “now make the heading larger” build on the previous turn, and it always works from the live canvas (so manual edits in between are respected).</P>
            <Banner status="warn" variant="inline" title="API key">
              Uses the same in-browser Anthropic API key as the AI image and icon tools, stored only in this browser. Fine for local prototyping — don’t ship the in-browser key to a public production build.
            </Banner>
          </Stack>
        ),
      },
    ],
  },

  {
    id: 'preview',
    title: 'Preview & prototype',
    icon: 'visibility',
    articles: [
      {
        id: 'views',
        title: 'Edit, Preview & Code views',
        keywords: 'edit preview code snippet json tabs view live render',
        body: (
          <Stack gap="sm">
            <Bullets items={[
              <><strong>Edit</strong> — the interactive canvas.</>,
              <><strong>Preview</strong> — a read-only render of the current page.</>,
              <><strong>Code snippet</strong> — the raw JSON, editable directly; the preview updates on every keystroke and invalid JSON shows the parse error inline.</>,
            ]} />
            <Shot
              name="editor-canvas"
              alt="The editor toolbar above the canvas showing the Edit, Preview, and Code snippet view switches."
              caption="The Edit / Preview / Code snippet switches sit in the toolbar above the canvas."
            />
          </Stack>
        ),
      },
      {
        id: 'prototype',
        title: 'Launching the prototype',
        keywords: 'prototype launch standalone share url navigate screens live sync open in new tab',
        body: (
          <Stack gap="sm">
            <P>Launch the prototype (the <Icon name="open_in_new" size="sm" /> action) to open the project in a new tab with no editor chrome — the generated navigation and in-page links work like a real multi-page site, and the address bar holds a shareable link to the current screen.</P>
            <P>While the prototype is open, edits you make in the editor live-sync to the screen on display.</P>
          </Stack>
        ),
      },
      {
        id: 'responsive-preview',
        title: 'Previewing at different screen sizes',
        keywords: 'responsive preview viewport breakpoint device width phone tablet desktop xs sm md lg xl resize fit',
        body: (
          <Stack gap="sm">
            <P>In the <strong>Preview</strong> view, a viewport selector resizes the canvas to common device widths — from phone to desktop — so you can check how the page responds at each breakpoint. The page is rendered with real media queries, so responsive components adapt exactly as they will when live.</P>
          </Stack>
        ),
      },
    ],
  },

  {
    id: 'storage',
    title: 'Saving, export & storage',
    icon: 'save',
    articles: [
      {
        id: 'autosave',
        title: 'Where your work is saved',
        keywords: 'save storage localstorage autosave persist browser local device cloud sync sign in account',
        body: (
          <Stack gap="sm">
            <P>There’s no save button — every change is saved automatically as you work. Where it lives depends on whether you’re signed in:</P>
            <Bullets items={[
              <><strong>Signed in</strong> — projects, pages, patterns, and themes sync to a shared cloud workspace in near-real-time, so your work is available on any device you sign in from.</>,
              <><strong>Signed out (or no account configured)</strong> — everything is saved in this browser only; it persists across reloads but stays on this device.</>,
            ]} />
          </Stack>
        ),
      },
      {
        id: 'accounts-sync',
        title: 'Accounts & the shared workspace',
        keywords: 'account sign in login cloud sync shared workspace supabase invite collaborate devices edit history who changed attribution',
        body: (
          <Stack gap="sm">
            <P>Accounts are <strong>invite-only</strong> — open <strong>Settings → Account</strong> to sign in. Once signed in, A1 is a <strong>shared workspace</strong>: every signed-in user sees and edits the same projects, pages, patterns, themes, and images.</P>
            <Bullets items={[
              'Changes sync automatically across devices and are visible to everyone signed in.',
              'Edits are attributed — the History panel shows who changed what, with restore.',
              <>The Account page’s <strong>Import local data</strong> action pushes anything stored only in this browser up to the shared workspace.</>,
            ]} />
            <Banner status="info" variant="inline" title="Not signed in?">
              Without an account (or when no backend is configured) the editor runs fully offline against this browser’s local storage — every feature still works, but your work stays on this device. Use Export to move it elsewhere.
            </Banner>
          </Stack>
        ),
      },
      {
        id: 'export-import',
        title: 'Export & import (backup)',
        keywords: 'export import backup download upload file projects pages restore transfer',
        body: <P>From <strong>Settings → Editor</strong>, <strong>Export all pages</strong> downloads every project and page as one text file; <strong>Import pages</strong> restores them. Use it as a backup or to move work to another browser or machine.</P>,
      },
    ],
  },

  {
    id: 'shortcuts',
    title: 'Keyboard shortcuts',
    icon: 'keyboard',
    articles: [
      {
        id: 'shortcuts-list',
        title: 'All keyboard shortcuts',
        keywords: 'keyboard shortcuts keys hotkeys undo redo delete duplicate group ungroup move copy paste pattern cmd ctrl',
        body: (
          <Stack gap="sm">
            <P>Press <Kbd>{`${MOD}K`}</Kbd> any time in the editor to see this list.</P>
            <DefinitionList
              size="sm"
              labelWidth="fixed"
              items={[
                { label: 'Undo', value: `${MOD}Z` },
                { label: 'Redo', value: `${MOD}${SHIFT}Z` },
                { label: 'Delete element', value: DEL },
                { label: 'Duplicate element', value: `${MOD}D` },
                { label: 'Group as Stack', value: `${MOD}G` },
                { label: 'Ungroup element', value: `${MOD}${SHIFT}G` },
                { label: 'Move element up', value: `${ALT}↑` },
                { label: 'Move element down', value: `${ALT}↓` },
                { label: 'Copy pattern (style)', value: `${MOD}${ALT}C` },
                { label: 'Paste pattern (style)', value: `${MOD}${ALT}V` },
                { label: 'Keyboard shortcuts', value: `${MOD}K` },
              ]}
            />
          </Stack>
        ),
      },
    ],
  },
  {
    id: 'backlog',
    title: 'Backlog & feedback',
    icon: 'task_alt',
    articles: [
      {
        id: 'file-a-ticket',
        title: 'Report a bug or request a feature',
        keywords: 'backlog ticket bug feature request report feedback flag create issue jira',
        body: (
          <Stack gap="sm">
            <P>
              The <strong>flag</strong> button in the top header opens a ticket from anywhere. Scoped
              buttons also live in the page editor toolbar, on each component page, and in the theme
              editor — those pre-fill what the ticket is about.
            </P>
            <P>Each ticket lets you choose a type and suggest a priority and complexity:</P>
            <Bullets items={[
              'Type — Bug, Feature, or Chore.',
              'Priority — P0 (critical) to P3 (someday). A suggestion; a maintainer confirms it.',
              'Complexity — XS to XL.',
              'Screenshots — attach images straight from the form.',
            ]} />
            <P>Open the <strong>Backlog</strong> page (Resources menu) to see everything.</P>
          </Stack>
        ),
      },
      {
        id: 'backlog-board',
        title: 'The board, statuses, and your queue',
        keywords: 'backlog board status queue vote upvote assign triage workflow new triaged accepted in progress done released',
        body: (
          <Stack gap="sm">
            <P>Tickets move through a workflow you can see on the <strong>Board</strong> tab:</P>
            <P><Kbd>New → Triaged → Accepted → In progress → Done → Released</Kbd> (plus Won't fix / Duplicate).</P>
            <Bullets items={[
              'Board — columns per status; open a ticket to change its status, priority, or assignee.',
              'All tickets — a sortable, filterable table of everything.',
              'My queue — tickets you created or are assigned, plus any awaiting your answer.',
              'Vote on a ticket to signal demand; sort the board by votes.',
              'A maintainer can ask the requester a clarifying question — it lands in their queue, and the header bell shows the unread count.',
              'Open a ticket to see it across tabs — Details, Comments (the thread + activity log), and Linked tickets (similar/merge).',
            ]} />
            <Shot
              name="backlog-board"
              alt="The Backlog page: Board / All tickets / My queue tabs, filter toolbars for Type, Priority, Size, Scope, and Sort, and a Swimlanes show/hide control above the status columns."
              caption="The Backlog — Board / All tickets / My queue tabs, filter toolbars, and the status swimlanes."
            />
          </Stack>
        ),
      },
      {
        id: 'backlog-merge-duplicates',
        title: 'Linking and merging duplicate tickets',
        keywords: 'backlog duplicate merge join link similar tickets same ai find combine de-dupe consolidate',
        body: (
          <Stack gap="sm">
            <P>
              Lots of tickets end up being the same request worded differently. Open a ticket
              and switch to the <strong>Linked tickets</strong> tab — it suggests likely
              matches, found locally as you go, no AI credits needed.
            </P>
            <Bullets items={[
              'Each suggestion shows how similar it is and why (shared terms, same scope).',
              'Merge… — join the two into one: choose which ticket to keep; the other is closed as a duplicate.',
              'The kept ticket absorbs the other’s comments, votes, and description — nothing is lost.',
              'Know the duplicate already? Use “Merge another ticket by ID” to link it directly.',
              'When you file a new ticket, possible duplicates are flagged so you can vote instead.',
            ]} />
            <P color="muted">
              A merged ticket shows a banner linking to the one it was merged into, and the
              survivor lists everything merged into it.
            </P>
          </Stack>
        ),
      },
      {
        id: 'backlog-local-sync',
        title: 'Working tickets locally',
        keywords: 'backlog sync pull push cli local agent triage tickets.json BACKLOG.md service role',
        body: (
          <Stack gap="sm">
            <P>
              Maintainers can pull the backlog into the repo to triage or implement tickets with an
              agent, then push changes back:
            </P>
            <Bullets items={[
              'npm run backlog:pull — writes backlog/tickets.json and a readable backlog/BACKLOG.md.',
              'Edit tickets.json (priority, complexity, status, description, or a newComment).',
              'npm run backlog:push — applies the edits and re-pulls.',
            ]} />
            <P color="muted">
              Needs SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY in apps/a1-web/.env. See backlog/README.md.
            </P>
          </Stack>
        ),
      },
    ],
  },
]

// ── Search ───────────────────────────────────────────────────────────────────────

function articleHaystack(category, article) {
  return `${category.title} ${article.title} ${article.keywords}`.toLowerCase()
}

function matchArticle(category, article, tokens) {
  if (!tokens.length) return true
  const hay = articleHaystack(category, article)
  return tokens.every((t) => hay.includes(t))
}

// ── Page ──────────────────────────────────────────────────────────────────────────

export function Help({ onNavigate }) {
  const [query, setQuery] = useState('')
  const [openIds, setOpenIds] = useState(() => new Set())

  const tokens = query.trim().toLowerCase().split(/\s+/).filter(Boolean)
  const searching = tokens.length > 0

  const filtered = useMemo(
    () =>
      HELP.map((category) => ({
        ...category,
        articles: category.articles.filter((a) => matchArticle(category, a, tokens)),
      })).filter((category) => category.articles.length > 0),
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [query],
  )

  const resultCount = filtered.reduce((sum, c) => sum + c.articles.length, 0)

  // In-page nav sections — one per currently-visible category. The category
  // headings carry matching `help-<id>` ids for PageNav's active-section tracking.
  const sections = useMemo(
    () => filtered.map((category) => ({ id: `help-${category.id}`, label: category.title, level: 1 })),
    [filtered],
  )

  function toggle(id) {
    setOpenIds((prev) => {
      const next = new Set(prev)
      if (next.has(id)) next.delete(id)
      else next.add(id)
      return next
    })
  }

  return (
    <>
      <Section padding="xs" contentWidth="xl" surface="panel" borderSize="sm" borderVariant="accent" borderSides="bottom">
        <Stack direction="column" gap="xs">
          <Breadcrumb
            items={[
              { label: 'Home', href: '/', onClick: (e) => { e?.preventDefault?.(); onNavigate?.('home') } },
              { label: 'Help' },
            ]}
          />
          <Heading as="h1" id="help-heading" size={{ xs: 'lg', md: 'xxl' }}>
            Help
          </Heading>
          <Paragraph size="sm" color="muted">
            How everything works.
          </Paragraph>
          <TextField
            label="Search help"
            type="search"
            autoComplete="off"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
          />
        </Stack>
      </Section>

      <Section padding="sm" contentWidth="xl" aria-labelledby="help-heading">
        <Stack direction="column" gap="lg">

        {searching && (
          <Paragraph size="sm" color="muted">
            {resultCount} {resultCount === 1 ? 'result' : 'results'} for “{query.trim()}”
          </Paragraph>
        )}

        {filtered.length === 0 ? (
          <MessageEmptyState
            icon="search_off"
            title="No matching help"
            description="Try a different word — e.g. “drag”, “prototype”, “shortcut”, or a component name."
            action={<Button variant="secondary" onClick={() => setQuery('')}>Clear search</Button>}
          />
        ) : (
          <Grid columns={{ xs: 1, lg: 4 }} gap="lg">
            <GridItem span={{ xs: 1, lg: 3 }}>
              <Stack direction="column" gap="lg">
                {filtered.map((category) => (
                  <Stack key={category.id} direction="column" gap="sm">
                    <Stack direction="row" gap="xs" align="center">
                      <Icon name={category.icon} color="accent" />
                      <Heading as="h2" size="md" id={`help-${category.id}`}>{category.title}</Heading>
                    </Stack>
                    {category.articles.map((article) => (
                      <Accordion
                        key={article.id}
                        label={article.title}
                        open={searching ? true : openIds.has(article.id)}
                        onChange={() => toggle(article.id)}
                      >
                        {article.body}
                      </Accordion>
                    ))}
                  </Stack>
                ))}
              </Stack>
            </GridItem>
            <GridItem span={{ xs: 1, lg: 1 }}>
              <PageNav sections={sections} label="Help topics" />
            </GridItem>
          </Grid>
        )}

        <Section padding="md" surface="panel" radius="md" gap="sm">
          <Heading as="h2" size="sm">Ready to build?</Heading>
          <Paragraph size="sm" color="muted">Jump into the editor and try these features on the sample project.</Paragraph>
          <ButtonContainer align="start">
            <Button icon="arrow_forward" onClick={() => onNavigate?.('editor')}>Open the editor</Button>
          </ButtonContainer>
        </Section>
      </Stack>
      </Section>
    </>
  )
}
