#!/usr/bin/env node
/**
 * Backlog local sync — pull the shared Supabase backlog down to the repo so an
 * agent or dev can triage/enrich/implement tickets locally, then push edits back.
 *
 *   node --env-file-if-exists=apps/a1-web/.env apps/a1-web/scripts/backlog-sync.mjs pull
 *   node --env-file-if-exists=apps/a1-web/.env apps/a1-web/scripts/backlog-sync.mjs push
 *
 * Or via the repo-root npm scripts: `npm run backlog:pull` / `npm run backlog:push`.
 *
 * Env (in apps/a1-web/.env): SUPABASE_URL (or VITE_SUPABASE_URL) and a
 * SUPABASE_SERVICE_ROLE_KEY (server-side key — bypasses RLS for admin/agent use;
 * never ship it to the browser). Output lands in repo-root `backlog/`:
 *   - tickets.json — structured, the file the agent edits, then `push`.
 *   - BACKLOG.md   — human/agent-readable, grouped by status then priority.
 *
 * Vocabularies mirror apps/a1-web/src/services/backlog/types.ts (keep in step).
 */
import { createClient } from '@supabase/supabase-js'
import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = resolve(HERE, '../../..')
const OUT_DIR = resolve(REPO_ROOT, 'backlog')
const JSON_PATH = resolve(OUT_DIR, 'tickets.json')
const MD_PATH = resolve(OUT_DIR, 'BACKLOG.md')

const STATUS_ORDER = ['new', 'triaged', 'accepted', 'in_progress', 'done', 'released', 'wont_fix', 'duplicate', 'cancelled']
const STATUS_LABELS = {
  new: 'New', triaged: 'Triaged', accepted: 'Accepted', in_progress: 'In progress',
  done: 'Done', released: 'Released', wont_fix: "Won't fix", duplicate: 'Duplicate', cancelled: 'Cancelled',
}
const PRIORITY_RANK = { p0: 0, p1: 1, p2: 2, p3: 3 }
// Fields the agent may edit in tickets.json and have pushed back.
const EDITABLE = ['title', 'description', 'type', 'status', 'priority', 'complexity', 'scopeKind', 'scopeRef', 'scopeLabel']

function getClient() {
  const url = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_KEY
  if (!url || !key) {
    console.error('Missing SUPABASE_URL and/or SUPABASE_SERVICE_ROLE_KEY.')
    console.error('Add them to apps/a1-web/.env (see apps/a1-web/.env.example).')
    process.exit(1)
  }
  return createClient(url, key, { auth: { persistSession: false } })
}

function itemFromRow(r, comments, refById) {
  return {
    id: r.id,
    number: r.number,
    ref: `A1-${r.number}`,
    title: r.title,
    description: r.description ?? '',
    type: r.type,
    status: r.status,
    priority: r.priority ?? null,
    complexity: r.complexity ?? null,
    scopeKind: r.scope_kind,
    scopeRef: r.scope_ref ?? null,
    scopeLabel: r.scope_label ?? null,
    assigneeEmail: r.assignee_email ?? null,
    awaitingRequester: !!r.awaiting_requester,
    // Read-only link (set by the in-app merge): the ticket this one was merged into.
    duplicateOf: r.duplicate_of ?? null,
    duplicateOfRef: r.duplicate_of ? (refById?.get(r.duplicate_of) ?? null) : null,
    votes: r.vote_count ?? 0,
    createdByEmail: r.created_by_email ?? null,
    createdAt: r.created_at,
    updatedAt: r.updated_at,
    // Agent triage scratch — set to append a comment to the thread on next push.
    newComment: '',
    comments: (comments || []).map((c) => ({
      kind: c.kind, body: c.body, userEmail: c.user_email, createdAt: c.created_at,
    })),
  }
}

async function fetchAll(sb) {
  const { data: items, error } = await sb.from('backlog_items').select('*').order('number', { ascending: true })
  if (error) throw error
  const { data: comments, error: cErr } = await sb.from('backlog_comments').select('*').order('created_at', { ascending: true })
  if (cErr) throw cErr
  const byItem = new Map()
  for (const c of comments || []) {
    if (!byItem.has(c.item_id)) byItem.set(c.item_id, [])
    byItem.get(c.item_id).push(c)
  }
  const refById = new Map((items || []).map((r) => [r.id, `A1-${r.number}`]))
  return (items || []).map((r) => itemFromRow(r, byItem.get(r.id), refById))
}

function toMarkdown(tickets) {
  const lines = []
  lines.push('# Backlog', '')
  lines.push('Generated by `npm run backlog:pull` from the Supabase backlog. **Do not edit this file** —')
  lines.push('edit `backlog/tickets.json` (change `priority`, `complexity`, `status`, `description`, or set')
  lines.push('`newComment` to add a thread reply), then run `npm run backlog:push`.', '')
  const open = tickets.filter((t) => !['released', 'wont_fix', 'duplicate', 'cancelled'].includes(t.status))
  lines.push(`_${tickets.length} tickets · ${open.length} open · pulled ${new Date().toISOString()}_`, '')

  for (const status of STATUS_ORDER) {
    const group = tickets
      .filter((t) => t.status === status)
      .sort((a, b) => (PRIORITY_RANK[a.priority] ?? 9) - (PRIORITY_RANK[b.priority] ?? 9) || a.number - b.number)
    if (!group.length) continue
    lines.push(`## ${STATUS_LABELS[status]} (${group.length})`, '')
    for (const t of group) {
      const tags = [t.type, t.priority || 'no-priority', t.complexity || 'no-size'].join(' · ')
      lines.push(`### ${t.ref} · ${t.title}  \`${tags}\``)
      const meta = []
      if (t.scopeKind && t.scopeKind !== 'general') meta.push(`Scope: ${t.scopeKind}${t.scopeLabel ? ` (${t.scopeLabel})` : ''}`)
      if (t.createdByEmail) meta.push(`by ${t.createdByEmail}`)
      meta.push(`${t.votes} votes`)
      if (t.awaitingRequester) meta.push('awaiting requester')
      if (t.duplicateOfRef) meta.push(`duplicate of ${t.duplicateOfRef}`)
      lines.push(`_${meta.join(' · ')}_`, '')
      if (t.description) lines.push(t.description, '')
      const qs = t.comments.filter((c) => c.kind === 'question' || c.kind === 'answer')
      if (qs.length) {
        lines.push('Q&A:')
        for (const c of qs) lines.push(`- **${c.kind}** (${c.userEmail || 'someone'}): ${c.body}`)
        lines.push('')
      }
    }
  }
  return lines.join('\n')
}

async function pull(sb) {
  const tickets = await fetchAll(sb)
  mkdirSync(OUT_DIR, { recursive: true })
  writeFileSync(JSON_PATH, JSON.stringify({ pulledAt: new Date().toISOString(), tickets }, null, 2))
  writeFileSync(MD_PATH, toMarkdown(tickets))
  console.log(`Pulled ${tickets.length} tickets → backlog/tickets.json + backlog/BACKLOG.md`)
}

async function push(sb) {
  if (!existsSync(JSON_PATH)) {
    console.error('No backlog/tickets.json — run `npm run backlog:pull` first.')
    process.exit(1)
  }
  const local = JSON.parse(readFileSync(JSON_PATH, 'utf8'))
  const current = await fetchAll(sb)
  const byId = new Map(current.map((t) => [t.id, t]))
  let updated = 0
  let commented = 0

  for (const t of local.tickets || []) {
    const db = byId.get(t.id)
    if (!db) { console.warn(`Skipping ${t.ref || t.id}: no longer in the backlog.`); continue }

    const patch = {}
    for (const field of EDITABLE) {
      if (t[field] !== undefined && t[field] !== db[field]) {
        const col = field.replace(/[A-Z]/g, (m) => `_${m.toLowerCase()}`) // camelCase → snake_case
        patch[col] = t[field] === '' && field === 'description' ? null : t[field]
      }
    }
    if (Object.keys(patch).length) {
      const { error } = await sb.from('backlog_items').update(patch).eq('id', t.id)
      if (error) console.warn(`Update failed for ${t.ref}:`, error.message)
      else { updated += 1; console.log(`Updated ${t.ref}: ${Object.keys(patch).join(', ')}`) }
    }

    const note = (t.newComment || '').trim()
    if (note) {
      const { error } = await sb.from('backlog_comments').insert({ item_id: t.id, kind: 'comment', body: note })
      if (error) console.warn(`Comment failed for ${t.ref}:`, error.message)
      else { commented += 1; console.log(`Commented on ${t.ref}`) }
    }
  }

  console.log(`Pushed: ${updated} updated, ${commented} comments added.`)
  // Re-pull so the local files reflect the new state and transient newComment fields clear.
  await pull(sb)
}

const cmd = process.argv[2]
const sb = getClient()
if (cmd === 'pull') await pull(sb)
else if (cmd === 'push') await push(sb)
else { console.error('Usage: backlog-sync.mjs <pull|push>'); process.exit(1) }
