import buttonRules from '../../../../../system/rules/button.yaml?raw'
import cardRules from '../../../../../system/rules/card.yaml?raw'
import pageLayoutRules from '../../../../../system/rules/page-layout.yaml?raw'
import sideNavRules from '../../../../../system/rules/side-nav.yaml?raw'
import messageBadgeRules from '../../../../../system/rules/message-badge.yaml?raw'
import definitionListRules from '../../../../../system/rules/definition-list.yaml?raw'
import circularProgressRules from '../../../../../system/rules/circular-progress.yaml?raw'
import stepTrackerRules from '../../../../../system/rules/step-tracker.yaml?raw'

export const LAST_UPDATED = '2026-06-15'
export const PACKAGE_COLUMNS = ['React', 'Native', 'Pure']

// Mirrors the "A1 Web menu hierarchy" section in system/ai/components.md.
export const componentCategories = [
  {
    id: 'typography',
    title: 'Typography',
    icon: 'title',
    body: 'Text primitives for hierarchy, prose, lists, separators, and inline semantic text.',
    components: [
      { id: 'heading', title: 'Heading', body: 'Semantic headings with display and heading scales.' },
      { id: 'paragraph', title: 'Paragraph', body: 'Body copy with responsive sizing, alignment, and muted states.' },
      { id: 'blockquote', title: 'Blockquote', body: 'Editorial quotation patterns with accent, pull, and ruled variants.' },
      { id: 'list', title: 'List', body: 'Ordered and unordered lists with tokenized rhythm and icons.' },
      { id: 'code', title: 'Code', body: 'Inline and block code treatments with wrapping and copy support.' },
      { id: 'divider', title: 'Divider', body: 'Horizontal and vertical separation for content groups.' },
      { id: 'inline', title: 'Inline', body: 'Code, keyboard, mark, and other inline text treatments.' },
    ],
  },
  {
    id: 'navigation',
    title: 'Navigation',
    icon: 'near_me',
    body: 'Wayfinding components for global, local, tabbed, and breadcrumb navigation.',
    components: [
      { id: 'link', title: 'Link', body: 'Accessible text links with semantic color and focus states.' },
      { id: 'breadcrumb', title: 'Breadcrumb', body: 'Hierarchical location trails for deep content.' },
      { id: 'side-nav', title: 'Side Nav', body: 'Responsive nested navigation for app shells.' },
      { id: 'top-header', title: 'Top Header', body: 'Global header with nav, actions, menus, and mobile drawer.' },
      { id: 'bottom-drawer', title: 'Bottom Drawer', body: 'Fixed mobile navigation bar with up to five icon-above-label items and badge counts.' },
      { id: 'tabs', title: 'Tabs', body: 'Tabbed navigation for related content panels.' },
      { id: 'page-nav', title: 'Page Nav', body: 'In-page navigation for long-form content.' },
      { id: 'tree-menu', title: 'Tree Menu', body: 'Hierarchical navigation with infinite nesting, icons, and keyboard support.' },
    ],
  },
  {
    id: 'actions',
    title: 'Actions',
    icon: 'touch_app',
    body: 'Controls that trigger commands, choices, and mode changes.',
    components: [
      { id: 'button', title: 'Button', body: 'Primary, secondary, tertiary, destructive, and success actions.' },
      { id: 'icon-button', title: 'Icon Button', body: 'Compact icon-only actions with accessible labels.' },
      { id: 'switch', title: 'Switch', body: 'Binary on/off settings and preferences.' },
      { id: 'segmented-control', title: 'Segmented Control', body: 'Small sets of mutually exclusive choices.' },
      { id: 'sticky-actions', title: 'Sticky Actions', body: 'Fixed bottom action bar for flows, wizards, and forms with contentWidth alignment.' },
    ],
  },
  {
    id: 'inputs',
    title: 'Inputs',
    icon: 'edit_note',
    body: 'Form controls for collecting, validating, and grouping user input.',
    components: [
      { id: 'text-field', title: 'Text Field', body: 'Single-line text, email, and password input with labels, hints, and validation.' },
      { id: 'number-field', title: 'Number Field', body: 'Numeric input with optional prefix and unit affordances.' },
      { id: 'date-field', title: 'Date Field', body: 'Native date input with A1 field styling.' },
      { id: 'time-field', title: 'Time Field', body: 'Native time input with A1 field styling.' },
      { id: 'phone-field', title: 'Phone Field', body: 'Masked telephone number input.' },
      { id: 'zip-field', title: 'Zip Field', body: 'Masked postal / ZIP code input.' },
      { id: 'credit-card-field', title: 'Credit Card Field', body: 'Masked credit card number input.' },
      { id: 'textarea', title: 'Textarea', body: 'Multi-line text entry with labels, hints, and validation.' },
      { id: 'select', title: 'Select', body: 'Native option selection with A1 field styling.' },
      { id: 'checkbox-group', title: 'Checkbox Group', body: 'Multi-select form choices grouped by fieldset.' },
      { id: 'radio-group', title: 'Radio Group', body: 'Single-select form choices grouped by fieldset.' },
      { id: 'choice-group', title: 'Choice Group', body: 'Card-tile selection with single or multi-select, icons, sections, and responsive columns.' },
      { id: 'fieldset', title: 'Fieldset', body: 'Semantic grouping for related form controls.' },
      { id: 'field-row', title: 'Field Row', body: 'Lays out related fields side by side, stacking on narrow viewports.' },
      { id: 'inline-editable', title: 'Inline Editable', body: 'Editable text that stays in reading context.' },
    ],
  },
  {
    id: 'feedback',
    title: 'Feedback',
    icon: 'campaign',
    body: 'Status, alert, notification, and empty-state components.',
    components: [
      { id: 'banner', title: 'Banner', body: 'Prominent page-level messages.' },
      { id: 'badge', title: 'Badge', body: 'Inline status chips for metadata and state.' },
      { id: 'notification', title: 'Notification', body: 'Compact count and status indicators.' },
      { id: 'snackbar', title: 'Snackbar', body: 'Transient confirmations and alerts.' },
      { id: 'empty-state', title: 'Empty State', body: 'Guidance for blank or unavailable content.' },
      { id: 'status-bar', title: 'Status Bar', body: 'Horizontal progress indicator for determinate and loading states.' },
      { id: 'circular-progress', title: 'Circular Progress', body: 'Circular ring progress indicator with static value display, inner content, and loading spinner.' },
      { id: 'step-tracker', title: 'Step Tracker', body: 'Non-interactive step position indicator with pill and dot states, four alignment options.' },
    ],
  },
  {
    id: 'layout',
    title: 'Layout',
    icon: 'dashboard',
    body: 'Composition primitives for page sections, grids, cards, spacing, and app shells.',
    components: [
      { id: 'section', title: 'Section', body: 'Full-width content bands with surfaces, padding, and alignment.' },
      { id: 'card', title: 'Card', body: 'Grouped content and navigation surfaces.' },
      { id: 'stack', title: 'Stack', body: 'One-dimensional spacing and alignment.' },
      { id: 'cluster', title: 'Cluster', body: 'Wrapping inline groups with tokenized gaps.' },
      { id: 'grid', title: 'Grid', body: 'Responsive grid layouts and bento arrangements.' },
      { id: 'bleed', title: 'Bleed', body: 'Content that reaches beyond a parent inset.' },
      { id: 'inset', title: 'Inset', body: 'Tokenized inner spacing wrappers.' },
      { id: 'spacer', title: 'Spacer', body: 'Explicit responsive spacing blocks.' },
      { id: 'page-layout', title: 'Page Layout', body: 'Header, sidebar, aside, main, and footer app shell layout.' },
      { id: 'button-container', title: 'Button Container', body: 'Responsive action grouping and alignment.' },
      { id: 'figure', title: 'Figure', body: 'Images or media with accessible captions.' },
    ],
  },
  {
    id: 'overlay',
    title: 'Overlay',
    icon: 'web_asset',
    body: 'Layered UI surfaces for dialogs and anchored menus.',
    components: [
      { id: 'dialog', title: 'Dialog', body: 'Modal interactions with focus management.' },
      { id: 'menu', title: 'Menu', body: 'Anchored command and navigation menus.' },
      { id: 'context-menu', title: 'Context Menu', body: 'Right-click menu portaled to the document body.' },
    ],
  },
  {
    id: 'data',
    title: 'Data',
    icon: 'table_chart',
    body: 'Components for tabular information, filtering, pagination, and date browsing.',
    components: [
      { id: 'data-table', title: 'Data Table', body: 'Sortable, selectable, responsive tabular data.' },
      { id: 'definition-list', title: 'Definition List', body: 'Semantic label/value pairs for metadata, summaries, and details.' },
      { id: 'pagination', title: 'Pagination', body: 'Paged navigation for long result sets.' },
      { id: 'calendar', title: 'Calendar', body: 'Month-grid date browser with scroll and paginated variants, localised labels, today highlight, and past-day dimming.' },
    ],
  },
  {
    id: 'media-iconography',
    title: 'Media and iconography',
    icon: 'insert_photo',
    body: 'Visual primitives for symbols and supporting media.',
    components: [
      { id: 'icon', title: 'Icon', body: 'Material Symbols wrapper with A1 sizing and color.' },
    ],
  },
  {
    id: 'disclosure',
    title: 'Disclosure',
    icon: 'unfold_more',
    body: 'Expandable content patterns.',
    components: [
      { id: 'accordion', title: 'Accordion', body: 'Expandable sections for progressive disclosure.' },
    ],
  },
]

export const PACKAGE_COVERAGE = {
  heading:            ['React', 'Native', 'Pure'],
  paragraph:          ['React', 'Native', 'Pure'],
  blockquote:         ['React', 'Native', 'Pure'],
  list:               ['React', 'Native', 'Pure'],
  code:               ['React'],
  divider:            ['React', 'Pure'],
  inline:             ['React', 'Pure'],
  link:               ['React', 'Native', 'Pure'],
  breadcrumb:         ['React'],
  'side-nav':         ['React', 'Native'],
  'top-header':       ['React', 'Pure'],
  'bottom-drawer':    ['React', 'Pure'],
  tabs:               ['React'],
  'page-nav':         ['React'],
  'tree-menu':        ['React'],
  button:             ['React', 'Native', 'Pure'],
  'icon-button':      ['React', 'Native', 'Pure'],
  switch:             ['React'],
  'segmented-control':['React'],
  'sticky-actions':   ['React'],
  'text-field':       ['React', 'Pure'],
  'number-field':     ['React'],
  'date-field':       ['React'],
  'time-field':       ['React'],
  'phone-field':      ['React'],
  'zip-field':        ['React'],
  'credit-card-field':['React'],
  textarea:           ['React', 'Pure'],
  select:             ['React', 'Pure'],
  'checkbox-group':   ['React', 'Pure'],
  'radio-group':      ['React', 'Pure'],
  fieldset:           ['React', 'Pure'],
  'field-row':        ['React'],
  'inline-editable':  ['React'],
  'choice-group':     ['React'],
  banner:             ['React', 'Native'],
  badge:              ['React', 'Native'],
  notification:       ['React'],
  snackbar:           ['React', 'Native'],
  'empty-state':      ['React', 'Native'],
  'status-bar':       ['React'],
  'circular-progress':['React', 'Pure'],
  'step-tracker':     ['React', 'Pure'],
  section:            ['React', 'Native', 'Pure'],
  card:               ['React', 'Native'],
  stack:              ['React'],
  cluster:            ['React'],
  grid:               ['React'],
  bleed:              ['React'],
  inset:              ['React'],
  spacer:             ['React'],
  'page-layout':      ['React'],
  'button-container': ['React', 'Native'],
  figure:             ['React', 'Pure'],
  dialog:             ['React', 'Native'],
  menu:               ['React'],
  'context-menu':     ['React'],
  'data-table':       ['React', 'Pure'],
  'definition-list':  ['React', 'Pure'],
  pagination:         ['React', 'Native'],
  calendar:           ['React'],
  icon:               ['React', 'Pure'],
  accordion:          ['React', 'Pure'],
}

// Component status — single point of truth for component maturity.
// Update here (and mirror in system/ai/components.md) when a component graduates.
// Values: 'stable' | 'beta' | 'experimental' | 'deprecated'
export const COMPONENT_STATUS = {
  heading:             'beta',
  paragraph:           'beta',
  blockquote:          'beta',
  list:                'beta',
  code:                'beta',
  divider:             'beta',
  inline:              'beta',
  link:                'beta',
  breadcrumb:          'beta',
  'side-nav':          'beta',
  'top-header':        'beta',
  'bottom-drawer':     'beta',
  tabs:                'beta',
  'page-nav':          'beta',
  'tree-menu':         'beta',
  button:              'beta',
  'icon-button':       'beta',
  switch:              'beta',
  'segmented-control': 'beta',
  'sticky-actions':    'beta',
  'text-field':        'beta',
  'number-field':      'beta',
  'date-field':        'beta',
  'time-field':        'beta',
  'phone-field':       'beta',
  'zip-field':         'beta',
  'credit-card-field': 'beta',
  textarea:            'beta',
  select:              'beta',
  'checkbox-group':    'beta',
  'radio-group':       'beta',
  fieldset:            'beta',
  'field-row':         'beta',
  'inline-editable':   'beta',
  'choice-group':      'beta',
  banner:              'beta',
  badge:               'beta',
  notification:        'beta',
  snackbar:            'beta',
  'empty-state':       'beta',
  'status-bar':        'beta',
  'circular-progress': 'beta',
  'step-tracker':      'beta',
  section:             'beta',
  card:                'beta',
  stack:               'beta',
  cluster:             'deprecated',
  grid:                'beta',
  bleed:               'beta',
  inset:               'beta',
  spacer:              'beta',
  'page-layout':       'beta',
  'button-container':  'beta',
  figure:              'beta',
  dialog:              'beta',
  menu:                'beta',
  'context-menu':      'beta',
  'data-table':        'beta',
  'definition-list':   'beta',
  pagination:          'beta',
  calendar:            'experimental',
  icon:                'beta',
  accordion:           'beta',
}

export const STATUS_META = {
  stable:       { status: 'success', label: 'Stable',       icon: 'check_circle', desc: 'Production-ready. API is stable and fully documented.' },
  beta:         { status: 'warn',    label: 'Beta',         icon: 'science',    desc: 'Available for use. API may evolve before the stable release.' },
  experimental: { status: 'info',    label: 'Experimental', icon: 'science',    desc: 'Proof of concept. Breaking changes are expected.' },
  deprecated:   { status: 'error',   label: 'Deprecated',   icon: 'block',      desc: 'Scheduled for removal. Migrate to the recommended alternative.' },
}

// Related components — curated by usage patterns and natural substitution/composition.
export const COMPONENT_RELATED = {
  heading:             ['paragraph', 'divider', 'section'],
  paragraph:           ['heading', 'blockquote', 'inline'],
  blockquote:          ['paragraph', 'divider'],
  list:                ['paragraph', 'divider'],
  code:                ['paragraph', 'button'],
  divider:             ['spacer', 'section'],
  inline:              ['paragraph', 'text-field'],
  link:                ['button', 'breadcrumb', 'page-nav'],
  breadcrumb:          ['link', 'page-nav'],
  'side-nav':          ['top-header', 'page-layout'],
  'top-header':        ['side-nav', 'page-layout', 'menu'],
  'bottom-drawer':     ['top-header', 'tabs', 'page-layout'],
  tabs:                ['segmented-control', 'page-nav'],
  'page-nav':          ['tabs', 'breadcrumb'],
  'tree-menu':         ['side-nav', 'accordion', 'menu'],
  button:              ['icon-button', 'button-container', 'link'],
  'icon-button':       ['button', 'icon'],
  switch:              ['checkbox-group', 'radio-group', 'segmented-control'],
  'segmented-control': ['tabs', 'switch', 'radio-group'],
  'sticky-actions':    ['button', 'button-container', 'step-tracker'],
  'text-field':        ['number-field', 'select', 'textarea', 'fieldset'],
  'number-field':      ['text-field', 'fieldset'],
  'date-field':        ['time-field', 'text-field', 'calendar'],
  'time-field':        ['date-field', 'text-field'],
  'phone-field':       ['text-field', 'zip-field'],
  'zip-field':         ['text-field', 'phone-field'],
  'credit-card-field': ['text-field', 'number-field'],
  textarea:            ['text-field', 'fieldset'],
  select:              ['text-field', 'radio-group'],
  'checkbox-group':    ['radio-group', 'fieldset', 'switch'],
  'radio-group':       ['checkbox-group', 'fieldset', 'switch'],
  fieldset:            ['field-row', 'text-field', 'checkbox-group'],
  'field-row':         ['fieldset', 'text-field', 'select'],
  'inline-editable':   ['text-field', 'textarea'],
  'choice-group':      ['checkbox-group', 'radio-group', 'segmented-control'],
  banner:              ['empty-state', 'badge'],
  badge:               ['banner', 'notification'],
  notification:        ['badge', 'icon'],
  snackbar:            ['banner', 'badge'],
  'empty-state':       ['banner', 'button', 'section'],
  'status-bar':        ['circular-progress', 'step-tracker'],

  section:             ['card', 'grid', 'stack'],
  card:                ['section', 'grid'],
  stack:               ['cluster', 'grid'],
  cluster:             ['stack', 'grid'],
  grid:                ['stack', 'section'],
  bleed:               ['section', 'inset'],
  inset:               ['section', 'spacer'],
  spacer:              ['inset', 'stack'],
  'page-layout':       ['section', 'side-nav', 'top-header'],
  'button-container':  ['button', 'stack'],
  figure:              ['card', 'section'],
  dialog:              ['menu', 'button'],
  menu:                ['dialog', 'context-menu', 'button'],
  'context-menu':      ['menu', 'dialog'],
  'circular-progress': ['status-bar', 'badge', 'icon'],
  'step-tracker':      ['tabs', 'status-bar', 'circular-progress'],
  'data-table':        ['definition-list', 'pagination', 'section'],
  'definition-list':   ['data-table', 'heading', 'icon-button'],
  pagination:          ['data-table'],
  calendar:            ['data-table', 'definition-list', 'date-field', 'pagination'],
  icon:                ['icon-button', 'badge'],
  accordion:           ['tabs', 'section'],
}

export const ruleSourceFiles = [
  { file: 'system/rules/button.yaml', raw: buttonRules },
  { file: 'system/rules/card.yaml', raw: cardRules },
  { file: 'system/rules/page-layout.yaml', raw: pageLayoutRules },
  { file: 'system/rules/side-nav.yaml', raw: sideNavRules },
  { file: 'system/rules/message-badge.yaml', raw: messageBadgeRules },
  { file: 'system/rules/definition-list.yaml', raw: definitionListRules },
  { file: 'system/rules/circular-progress.yaml', raw: circularProgressRules },
  { file: 'system/rules/step-tracker.yaml', raw: stepTrackerRules },
]
