import buttonRules from '../../../../../system/rules/button.yaml?raw'
import actionTileRules from '../../../../../system/rules/action-tile.yaml?raw'
import chipRules from '../../../../../system/rules/chip.yaml?raw'
import cardRules from '../../../../../system/rules/card.yaml?raw'
import pageLayoutRules from '../../../../../system/rules/page-layout.yaml?raw'
import sideNavRules from '../../../../../system/rules/side-nav.yaml?raw'
import messageBadgeRules from '../../../../../system/rules/message-badge.yaml?raw'
import definitionListRules from '../../../../../system/rules/definition-list.yaml?raw'
import circularProgressRules from '../../../../../system/rules/circular-progress.yaml?raw'
import stepTrackerRules from '../../../../../system/rules/step-tracker.yaml?raw'
import toolbarRules from '../../../../../system/rules/toolbar.yaml?raw'
import sectionRules from '../../../../../system/rules/section.yaml?raw'
import tooltipRules from '../../../../../system/rules/tooltip.yaml?raw'
import overlayRules from '../../../../../system/rules/overlay.yaml?raw'
import chartRules from '../../../../../system/rules/chart.yaml?raw'

export const LAST_UPDATED = '2026-06-17'
export const COMPONENT_LAST_UPDATED = {
  'line-chart': '2026-07-06',
  'bar-chart': '2026-07-06',
  'area-chart': '2026-07-06',
  'composed-chart': '2026-07-06',
  'pie-chart': '2026-07-06',
  'scatter-chart': '2026-07-06',
  'radar-chart': '2026-07-06',
  'radial-bar-chart': '2026-07-06',
  'funnel-chart': '2026-07-06',
  'treemap-chart': '2026-07-06',
  'sankey-chart': '2026-07-06',
  'sunburst-chart': '2026-07-06',
  dialog: '2026-07-06',
  menu: '2026-07-06',
  'text-field': '2026-07-06',
  textarea: '2026-07-06',
  button: '2026-07-06',
  overlay: '2026-07-05',
  'tree-menu': '2026-07-05',
  snackbar: '2026-07-05',
  chip: '2026-07-02',
  'action-tile': '2026-07-02',
  stat: '2026-06-30',
  'top-header': '2026-06-27',
  icon: '2026-06-25',
  canvas: '2026-06-23',
  node: '2026-06-23',
  toolbar: '2026-06-23',
  figure: '2026-06-16',
  slider: '2026-06-16',
  section: '2026-06-17',
  accordion: '2026-06-16',
  'icon-button': '2026-06-15',
  'context-menu': '2026-06-15',
  banner: '2026-06-15',
  badge: '2026-06-15',
  'empty-state': '2026-06-15',
  pagination: '2026-06-15',
  'bottom-drawer': '2026-06-15',
  'data-table': '2026-06-10',
  'button-container': '2026-06-10',
  'circular-progress': '2026-06-09',
  'definition-list': '2026-06-09',
  'status-bar': '2026-06-09',
  calendar: '2026-06-07',
}
export const PACKAGE_COLUMNS = ['React', 'Native', 'Pure', 'Web Components', 'Figma']

// Mirrors the "A1 Web menu hierarchy" section in packages/react/ai/components.md.
export const componentCategories = [
  {
    id: 'layout',
    title: 'Layout & Display',
    icon: 'dashboard',
    body: 'Composition primitives for page sections, grids, cards, spacing, and app shells.',
    components: [
      { id: 'section', icon: 'crop_free', title: 'Section', body: 'Full-width content bands with surfaces, padding, and alignment.' },
      { id: 'card', icon: 'article', title: 'Card', body: 'Grouped content and navigation surfaces.' },
      { id: 'stack', icon: 'view_agenda', title: 'Stack', body: 'One-dimensional spacing and alignment.' },
      { id: 'grid', icon: 'grid_view', title: 'Grid', body: 'Responsive grid layouts and bento arrangements.' },
      { id: 'bleed', icon: 'open_in_full', title: 'Bleed', body: 'Content that reaches beyond a parent inset.' },
      { id: 'inset', icon: 'padding', title: 'Inset', body: 'Tokenized inner spacing wrappers.' },
      { id: 'spacer', icon: 'space_bar', title: 'Spacer', body: 'Explicit responsive spacing blocks.' },
      { id: 'page-layout', icon: 'space_dashboard', title: 'Page Layout', body: 'Header, sidebar, aside, main, and footer app shell layout.' },
      { id: 'button-container', icon: 'view_week', title: 'Button Container', body: 'Responsive action grouping and alignment.' },
      { id: 'canvas', icon: 'polyline', title: 'Canvas', body: 'Infinite pan/zoom canvas for visualizing node graphs with labeled circles, shapes, and directional connectors.' },
    ],
  },
  {
    id: 'typography',
    title: 'Typography',
    icon: 'title',
    body: 'Text primitives for hierarchy, prose, lists, separators, and inline semantic text.',
    components: [
      { id: 'heading', icon: 'title', title: 'Heading', body: 'Semantic headings with display and heading scales.' },
      { id: 'paragraph', icon: 'notes', title: 'Paragraph', body: 'Body copy with responsive sizing, alignment, and muted states.' },
      { id: 'blockquote', icon: 'format_quote', title: 'Blockquote', body: 'Editorial quotation patterns with accent, pull, and ruled variants.' },
      { id: 'list', icon: 'format_list_bulleted', title: 'List', body: 'Ordered and unordered lists with tokenized rhythm and icons.' },
      { id: 'code', icon: 'code', title: 'Code', body: 'Inline and block code treatments with wrapping and copy support.' },
      { id: 'divider', icon: 'horizontal_rule', title: 'Divider', body: 'Horizontal and vertical separation for content groups.' },
      { id: 'inline', icon: 'format_size', title: 'Inline', body: 'Code, keyboard, mark, and other inline text treatments.' },
    ],
  },
  {
    id: 'actions',
    title: 'Actions & Controls',
    icon: 'touch_app',
    body: 'Controls that trigger commands, choices, mode changes, disclosure, and navigation between views.',
    components: [
      { id: 'button', icon: 'smart_button', title: 'Button', body: 'Primary, secondary, tertiary, destructive, and success actions.' },
      { id: 'action-tile', icon: 'apps', title: 'Action Tiles', body: 'Grouped icon-led action surfaces with grid or stack layouts and optional gap.' },
      { id: 'chip', icon: 'label', title: 'Chip', body: 'Compact filters, selectable tags, menu triggers, and navigation chips.' },
      { id: 'icon-button', icon: 'touch_app', title: 'Icon Button', body: 'Compact icon-only actions with accessible labels.' },
      { id: 'switch', icon: 'toggle_on', title: 'Switch', body: 'Binary on/off settings and preferences.' },
      { id: 'segmented-control', icon: 'splitscreen', title: 'Segmented Control', body: 'Small sets of mutually exclusive choices.' },
      { id: 'slider', icon: 'tune', title: 'Slider', body: 'Pick a value along a range, with optional labeled detents (None / XS / SM / LG).' },
      { id: 'toolbar', icon: 'build', title: 'Toolbar', body: 'Compact container for grouped editing controls — toggles, button groups, grids, selects, and dividers.' },
      { id: 'sticky-actions', icon: 'vertical_align_bottom', title: 'Sticky Actions', body: 'Fixed bottom action bar for flows, wizards, and forms with contentWidth alignment.' },
      { id: 'accordion', icon: 'unfold_more', title: 'Accordion', body: 'Expandable sections for progressive disclosure.' },
      { id: 'tabs', icon: 'tab', title: 'Tabs', body: 'Tabbed navigation for related content panels.' },
      { id: 'link', icon: 'link', title: 'Link', body: 'Accessible text links with semantic color and focus states.' },
    ],
  },
  {
    id: 'navigation',
    title: 'Navigation',
    icon: 'near_me',
    body: 'Wayfinding components for global, local, and breadcrumb navigation.',
    components: [
      { id: 'breadcrumb', icon: 'chevron_right', title: 'Breadcrumb', body: 'Hierarchical location trails for deep content.' },
      { id: 'side-nav', icon: 'view_sidebar', title: 'Side Nav', body: 'Responsive nested navigation for app shells.' },
      { id: 'top-header', icon: 'web_asset', title: 'Top Header', body: 'Global header with nav, actions, menus, and mobile drawer.' },
      { id: 'bottom-drawer', icon: 'call_to_action', title: 'Bottom Drawer', body: 'Fixed mobile navigation bar with up to five icon-above-label items and badge counts.' },
      { id: 'page-nav', icon: 'toc', title: 'Page Nav', body: 'In-page navigation for long-form content.' },
      { id: 'tree-menu', icon: 'account_tree', title: 'Tree Menu', body: 'Hierarchical navigation with infinite nesting, icons, and keyboard support.' },
    ],
  },
  {
    id: 'inputs',
    title: 'Inputs',
    icon: 'edit_note',
    body: 'Form controls for collecting, validating, and grouping user input.',
    components: [
      { id: 'text-field', icon: 'text_fields', title: 'Text Field', body: 'Single-line text, email, and password input with labels, hints, and validation.' },
      { id: 'search-field', icon: 'search', title: 'Search Field', body: 'Search input with a leading search icon and a trailing clear button.' },
      { id: 'number-field', icon: 'pin', title: 'Number Field', body: 'Numeric input with optional prefix and unit affordances.' },
      { id: 'date-field', icon: 'event', title: 'Date Field', body: 'Native date input with A1 field styling.' },
      { id: 'time-field', icon: 'schedule', title: 'Time Field', body: 'Native time input with A1 field styling.' },
      { id: 'phone-field', icon: 'phone', title: 'Phone Field', body: 'Masked telephone number input.' },
      { id: 'zip-field', icon: 'local_post_office', title: 'Zip Field', body: 'Masked postal / ZIP code input.' },
      { id: 'credit-card-field', icon: 'credit_card', title: 'Credit Card Field', body: 'Masked credit card number input.' },
      { id: 'textarea', icon: 'subject', title: 'Textarea', body: 'Multi-line text entry with labels, hints, and validation.' },
      { id: 'select', icon: 'arrow_drop_down_circle', title: 'Select', body: 'Native option selection with A1 field styling.' },
      { id: 'autocomplete', icon: 'manage_search', title: 'Autocomplete', body: 'Filtering combobox in single or multi-select, with optional create-your-own.' },
      { id: 'checkbox-group', icon: 'check_box', title: 'Checkbox Group', body: 'Multi-select form choices grouped by fieldset.' },
      { id: 'radio-group', icon: 'radio_button_checked', title: 'Radio Group', body: 'Single-select form choices grouped by fieldset.' },
      { id: 'choice-group', icon: 'dashboard_customize', title: 'Choice Group', body: 'Card-tile selection with single or multi-select, icons, sections, and responsive columns.' },
      { id: 'fieldset', icon: 'check_box_outline_blank', title: 'Fieldset', body: 'Semantic grouping for related form controls.' },
      { id: 'field-row', icon: 'table_rows', title: 'Field Row', body: 'Lays out related fields side by side, stacking on narrow viewports.' },
      { id: 'inline-editable', icon: 'edit', title: 'Inline Editable', body: 'Editable text that stays in reading context.' },
    ],
  },
  {
    id: 'feedback',
    title: 'Feedback & Messaging',
    icon: 'campaign',
    body: 'Status, alert, notification, and empty-state components.',
    components: [
      { id: 'banner', icon: 'view_day', title: 'Banner', body: 'Prominent page-level messages.' },
      { id: 'badge', icon: 'label', title: 'Badge', body: 'Inline status chips for metadata and state.' },
      { id: 'notification', icon: 'notifications', title: 'Notification', body: 'Compact count and status indicators.' },
      { id: 'snackbar', icon: 'notification_important', title: 'Snackbar', body: 'Transient confirmations and alerts.' },
      { id: 'empty-state', icon: 'inbox', title: 'Empty State', body: 'Guidance for blank or unavailable content.' },
      { id: 'status-bar', icon: 'linear_scale', title: 'Status Bar', body: 'Horizontal progress indicator for determinate and loading states.' },
      { id: 'circular-progress', icon: 'donut_large', title: 'Circular Progress', body: 'Circular ring progress indicator with static value display, inner content, and loading spinner.' },
      { id: 'step-tracker', icon: 'more_horiz', title: 'Step Tracker', body: 'Non-interactive step position indicator with pill and dot states, four alignment options.' },
    ],
  },
  {
    id: 'media-iconography',
    title: 'Media and iconography',
    icon: 'insert_photo',
    body: 'Visual primitives for media, symbols, and supporting imagery.',
    components: [
      { id: 'figure', icon: 'image', title: 'Figure', body: 'Images or media with accessible captions.' },
      { id: 'icon', icon: 'interests', title: 'Icon', body: 'Material Symbols and registered custom-font wrapper with A1 sizing and color.' },
    ],
  },
  {
    id: 'overlay',
    title: 'Overlay',
    icon: 'web_asset',
    body: 'Layered UI surfaces for dialogs and anchored menus.',
    components: [
      { id: 'dialog', icon: 'picture_in_picture', title: 'Dialog', body: 'Modal interactions with focus management.' },
      { id: 'overlay', icon: 'fullscreen', title: 'Overlay', body: 'Full-screen status overlay for bold messages and modal announcements.' },
      { id: 'menu', icon: 'menu', title: 'Menu', body: 'Anchored command and navigation menus.' },
      { id: 'context-menu', icon: 'more_vert', title: 'Context Menu', body: 'Right-click menu portaled to the document body.' },
      { id: 'tooltip', icon: 'tooltip', title: 'Tooltip', body: 'Brief, non-interactive context shown on hover or focus.' },
      { id: 'bottom-sheet', icon: 'swipe_up', title: 'Bottom Sheet', bareDisplay: true, body: 'Fixed, scrim-less bottom panel with a draggable handle; xs and sm only.' },
    ],
  },
  {
    id: 'data-viz',
    title: 'Data Viz',
    icon: 'query_stats',
    body: 'Components for node graphs, Cartesian charts, polar charts, categorical charts, and hierarchical data visualizations.',
    components: [
      { id: 'node',     icon: 'circle',         title: 'Node',     body: 'Standalone labeled shape component — circle, square, squircle, or rectangle — used directly or inside a Canvas.' },
      { id: 'line-chart', icon: 'show_chart', title: 'Line Chart', body: 'Token-styled Recharts line chart for trends over an ordered axis.' },
      { id: 'bar-chart', icon: 'bar_chart', title: 'Bar Chart', body: 'Token-styled Recharts bar chart for grouped or stacked comparisons.' },
      { id: 'area-chart', icon: 'area_chart', title: 'Area Chart', body: 'Token-styled Recharts area chart for cumulative or banded trends.' },
      { id: 'composed-chart', icon: 'stacked_line_chart', title: 'Composed Chart', body: 'Token-styled Recharts chart that mixes line, bar, and area series.' },
      { id: 'pie-chart', icon: 'pie_chart', title: 'Pie Chart', body: 'Token-styled Recharts pie chart for categorical share.' },
      { id: 'scatter-chart', icon: 'scatter_plot', title: 'Scatter Chart', body: 'Token-styled Recharts scatter plot for comparing numeric dimensions.' },
      { id: 'radar-chart', icon: 'radar', title: 'Radar Chart', body: 'Token-styled Recharts radar chart for multivariate profiles.' },
      { id: 'radial-bar-chart', icon: 'donut_large', title: 'Radial Bar Chart', body: 'Token-styled Recharts radial bar chart for circular progress comparisons.' },
      { id: 'funnel-chart', icon: 'filter_alt', title: 'Funnel Chart', body: 'Token-styled Recharts funnel chart for stage conversion.' },
      { id: 'treemap-chart', icon: 'view_quilt', title: 'Treemap Chart', body: 'Token-styled Recharts treemap for nested part-to-whole comparisons.' },
      { id: 'sankey-chart', icon: 'schema', title: 'Sankey Chart', body: 'Token-styled Recharts sankey diagram for proportional flows.' },
      { id: 'sunburst-chart', icon: 'wb_twilight', title: 'Sunburst Chart', body: 'Token-styled Recharts sunburst chart for radial hierarchy.' },
    ],
  },
  {
    id: 'data',
    title: 'Data',
    icon: 'table_chart',
    body: 'Components for tabular information, filtering, pagination, metrics, and date browsing.',
    components: [
      { id: 'data-table', icon: 'table_chart', title: 'Data Table', body: 'Sortable, selectable, responsive tabular data.' },
      { id: 'stat', icon: 'analytics', title: 'Stat', body: 'Single metric display with label, value, context, and optional badge.' },
      { id: 'definition-list', icon: 'format_list_numbered', title: 'Definition List', body: 'Semantic label/value pairs for metadata, summaries, and details.' },
      { id: 'pagination', icon: 'last_page', title: 'Pagination', body: 'Paged navigation for long result sets.' },
      { id: 'calendar', icon: 'calendar_month', title: 'Calendar', body: 'Month-grid date browser with scroll and paginated variants, localised labels, today highlight, and past-day dimming.' },
    ],
  },
]

// Canonical component → Material Symbols icon map, derived from
// `componentCategories`. This is the single source of truth for the icon that
// represents a component anywhere in the app (component browser, editor Add
// panel, layers tree, etc.). See system/icons/icon-usage.md.
export const COMPONENT_ICONS = Object.fromEntries(
  componentCategories.flatMap((category) => category.components.map((component) => [component.id, component.icon])),
)

export const COMPONENT_SEARCH_KEYWORDS = {
  heading: ['title', 'headline', 'h1', 'h2', 'display text', 'hero text'],
  paragraph: ['body copy', 'copy', 'text', 'prose', 'description'],
  blockquote: ['quote', 'citation', 'pull quote', 'testimonial'],
  list: ['bullets', 'bullet list', 'numbered list', 'ordered list', 'unordered list'],
  code: ['snippet', 'pre', 'kbd', 'keyboard', 'developer'],
  divider: ['rule', 'separator', 'line', 'horizontal rule'],
  inline: ['mark', 'highlight', 'keyboard', 'kbd', 'semantic text'],
  link: ['anchor', 'href', 'url', 'text link', 'navigation link'],
  breadcrumb: ['crumbs', 'trail', 'path', 'hierarchy'],
  'side-nav': ['sidebar', 'navigation', 'nav', 'left nav', 'menu'],
  'top-header': ['header', 'navbar', 'global nav', 'masthead', 'app bar'],
  'bottom-drawer': ['mobile nav', 'bottom nav', 'drawer', 'tab bar'],
  tabs: ['tablist', 'tab panel', 'section switcher'],
  'page-nav': ['toc', 'table of contents', 'in page nav', 'anchor nav'],
  'tree-menu': ['tree', 'nested nav', 'hierarchy', 'folder tree', 'outline'],
  button: ['cta', 'call to action', 'action', 'submit', 'primary action', 'cancel', 'buton', 'buttn'],
  'icon-button': ['icon action', 'close button', 'toolbar button', 'kebab', 'overflow button'],
  switch: ['toggle', 'on off', 'setting', 'preference'],
  'segmented-control': ['segment', 'toggle group', 'button group', 'mode switcher'],
  slider: ['range', 'scrubber', 'numeric range', 'control'],
  toolbar: ['tools', 'editor tools', 'command bar', 'format bar'],
  'sticky-actions': ['footer actions', 'fixed actions', 'bottom actions'],
  accordion: ['accordian', 'disclosure', 'expand collapse', 'details', 'faq'],
  'text-field': ['input', 'textfield', 'text input', 'form field', 'single line'],
  'search-field': ['search', 'find', 'filter input', 'query', 'lookup'],
  'number-field': ['number input', 'numeric', 'quantity', 'amount'],
  'date-field': ['date input', 'calendar input', 'day picker'],
  'time-field': ['time input', 'schedule input'],
  'phone-field': ['phone input', 'telephone', 'tel', 'mobile number'],
  'zip-field': ['zip input', 'postal code', 'postcode'],
  'credit-card-field': ['card number', 'payment card', 'cc input'],
  textarea: ['text area', 'multi line', 'multiline', 'long text', 'comment box'],
  select: ['dropdown', 'native select', 'option menu', 'picklist'],
  autocomplete: ['combobox', 'typeahead', 'suggestions', 'lookup'],
  'checkbox-group': ['checkboxes', 'multi select', 'check list'],
  'radio-group': ['radio buttons', 'single select', 'choice list'],
  'choice-group': ['cards', 'tile choice', 'selection cards', 'option cards'],
  fieldset: ['field group', 'legend', 'form group'],
  'field-row': ['form row', 'inline fields', 'field layout'],
  'inline-editable': ['inline edit', 'editable text', 'edit in place'],
  banner: ['alert', 'notice', 'message', 'callout'],
  badge: ['chip', 'label', 'pill', 'tag', 'status chip'],
  notification: ['indicator', 'count', 'badge count', 'unread'],
  snackbar: ['toast', 'confirmation', 'temporary message'],
  'empty-state': ['blank state', 'no results', 'placeholder', 'empty'],
  'status-bar': ['progress bar', 'linear progress', 'loading bar'],
  'circular-progress': ['spinner', 'loader', 'progress ring', 'loading'],
  'step-tracker': ['steps', 'stepper', 'wizard progress'],
  section: ['region', 'content band', 'page section', 'container'],
  card: ['tile', 'panel', 'surface', 'content card'],
  stack: ['vertical layout', 'horizontal layout', 'flex', 'spacing'],
  grid: ['layout grid', 'columns', 'rows', 'responsive grid', 'bento', 'grd'],
  bleed: ['full bleed', 'edge to edge', 'breakout'],
  inset: ['padding', 'inner spacing', 'content inset'],
  spacer: ['space', 'gap', 'vertical rhythm'],
  'page-layout': ['app shell', 'layout shell', 'sidebar layout', 'main layout'],
  'button-container': ['action group', 'button group', 'actions row'],
  canvas: ['diagram', 'node graph', 'flow', 'map', 'whiteboard'],
  figure: ['image', 'media', 'caption', 'photo'],
  dialog: ['modal', 'popup', 'confirmation dialog', 'window'],
  overlay: ['full screen dialog', 'modal overlay', 'game notification', 'status overlay', 'completion message'],
  menu: ['dropdown menu', 'popover menu', 'commands'],
  'context-menu': ['right click', 'shortcut menu', 'more menu'],
  'bottom-sheet': ['sheet', 'mobile panel', 'bottom panel'],
  'data-table': ['table', 'data grid', 'datagrid', 'grid', 'spreadsheet', 'rows', 'columns', 'sortable', 'filterable', 'datatable', 'data tabel'],
  'line-chart': ['recharts', 'data visualization', 'data viz', 'line graph', 'trend chart', 'graph', 'analytics'],
  'bar-chart': ['recharts', 'data visualization', 'data viz', 'bar graph', 'column chart', 'stacked chart', 'comparison', 'analytics'],
  'area-chart': ['recharts', 'data visualization', 'data viz', 'area graph', 'stacked area', 'trend chart', 'analytics'],
  'composed-chart': ['recharts', 'data visualization', 'data viz', 'combo chart', 'mixed chart', 'line chart', 'bar chart', 'area chart', 'analytics'],
  'pie-chart': ['recharts', 'data visualization', 'data viz', 'pie graph', 'share chart', 'proportion', 'category share'],
  'scatter-chart': ['recharts', 'data visualization', 'data viz', 'scatter plot', 'correlation', 'bubble chart', 'xy chart'],
  'radar-chart': ['recharts', 'data visualization', 'data viz', 'spider chart', 'polar chart', 'profile chart'],
  'radial-bar-chart': ['recharts', 'data visualization', 'data viz', 'radial bar', 'circular bar', 'progress comparison'],
  'funnel-chart': ['recharts', 'data visualization', 'data viz', 'conversion funnel', 'pipeline stages'],
  'treemap-chart': ['recharts', 'data visualization', 'data viz', 'tree map', 'hierarchy', 'nested rectangles'],
  'sankey-chart': ['recharts', 'data visualization', 'data viz', 'flow diagram', 'journey flow', 'proportional flow'],
  'sunburst-chart': ['recharts', 'data visualization', 'data viz', 'sunburst', 'radial hierarchy', 'taxonomy'],
  'definition-list': ['metadata', 'key value', 'description list', 'summary list'],
  pagination: ['pages', 'pager', 'next previous', 'page controls'],
  calendar: ['date grid', 'month', 'datepicker', 'date picker'],
  node: ['shape', 'graph node', 'diagram node'],
  icon: ['symbol', 'glyph', 'material symbol', 'custom icon'],
}

export const PACKAGE_COVERAGE = {
  heading:            ['React', 'Native', 'Pure'],
  paragraph:          ['React', 'Native', 'Pure'],
  blockquote:         ['React', 'Native', 'Pure'],
  list:               ['React', 'Native', 'Pure'],
  code:               ['React'],
  divider:            ['React', 'Pure'],
  inline:             ['React', 'Pure'],
  link:               ['React', 'Native', 'Pure'],
  breadcrumb:         ['React'],
  'side-nav':         ['React', 'Native'],
  'top-header':       ['React', 'Pure'],
  'bottom-drawer':    ['React', 'Pure'],
  tabs:               ['React'],
  'page-nav':         ['React'],
  'tree-menu':        ['React'],
  button:             ['React', 'Native', 'Pure', 'Web Components', 'Figma'],
  'action-tile':      ['React'],
  chip:               ['React'],
  'icon-button':      ['React', 'Native', 'Pure'],
  switch:             ['React'],
  'segmented-control':['React'],
  slider:             ['React'],
  toolbar:            ['React'],
  'sticky-actions':   ['React'],
  'text-field':       ['React', 'Pure', 'Figma'],
  'search-field':     ['React'],
  'number-field':     ['React'],
  'date-field':       ['React'],
  'time-field':       ['React'],
  'phone-field':      ['React'],
  'zip-field':        ['React'],
  'credit-card-field':['React'],
  textarea:           ['React', 'Pure'],
  select:             ['React', 'Pure'],
  autocomplete:       ['React'],
  'checkbox-group':   ['React', 'Pure'],
  'radio-group':      ['React', 'Pure'],
  fieldset:           ['React', 'Pure'],
  'field-row':        ['React'],
  'inline-editable':  ['React'],
  'choice-group':     ['React'],
  banner:             ['React', 'Native'],
  badge:              ['React', 'Native'],
  notification:       ['React'],
  snackbar:           ['React', 'Native', 'Web Components'],
  'empty-state':      ['React', 'Native'],
  'status-bar':       ['React'],
  'circular-progress':['React', 'Pure'],
  'step-tracker':     ['React', 'Pure'],
  section:            ['React', 'Native', 'Pure'],
  card:               ['React', 'Native'],
  stack:              ['React'],
  grid:               ['React'],
  bleed:              ['React'],
  inset:              ['React'],
  spacer:             ['React'],
  'page-layout':      ['React'],
  'button-container': ['React', 'Native'],
  canvas:             ['React'],
  figure:             ['React', 'Pure'],
  dialog:             ['React', 'Native', 'Figma'],
  overlay:            ['React'],
  menu:               ['React', 'Figma'],
  'context-menu':     ['React'],
  tooltip:            ['React', 'Pure'],
  'data-table':       ['React', 'Pure'],
  'line-chart':       ['React'],
  'bar-chart':        ['React'],
  'area-chart':       ['React'],
  'composed-chart':   ['React'],
  'pie-chart':        ['React'],
  'scatter-chart':    ['React'],
  'radar-chart':      ['React'],
  'radial-bar-chart': ['React'],
  'funnel-chart':     ['React'],
  'treemap-chart':    ['React'],
  'sankey-chart':     ['React'],
  'sunburst-chart':   ['React'],
  stat:               ['React'],
  'definition-list':  ['React', 'Pure'],
  pagination:         ['React', 'Native'],
  calendar:           ['React'],
  node:               ['React'],
  icon:               ['React', 'Pure'],
  accordion:          ['React', 'Pure'],
}

// Component status — single point of truth for component maturity.
// Update here (and mirror in system/ai/components.md) when a component graduates.
// Values: 'stable' | 'beta' | 'experimental' | 'deprecated'
export const COMPONENT_STATUS = {
  heading:             'beta',
  paragraph:           'beta',
  blockquote:          'beta',
  list:                'beta',
  code:                'beta',
  divider:             'beta',
  inline:              'beta',
  link:                'beta',
  breadcrumb:          'beta',
  'side-nav':          'beta',
  'top-header':        'beta',
  'bottom-drawer':     'beta',
  tabs:                'beta',
  'page-nav':          'beta',
  'tree-menu':         'beta',
  button:              'beta',
  'action-tile':       'experimental',
  chip:                'experimental',
  'icon-button':       'beta',
  switch:              'beta',
  'segmented-control': 'beta',
  slider:              'experimental',
  toolbar:             'experimental',
  'sticky-actions':    'beta',
  'text-field':        'beta',
  'search-field':      'beta',
  'number-field':      'beta',
  'date-field':        'beta',
  'time-field':        'beta',
  'phone-field':       'beta',
  'zip-field':         'beta',
  'credit-card-field': 'beta',
  textarea:            'beta',
  select:              'beta',
  autocomplete:        'beta',
  'checkbox-group':    'beta',
  'radio-group':       'beta',
  fieldset:            'beta',
  'field-row':         'beta',
  'inline-editable':   'beta',
  'choice-group':      'beta',
  banner:              'beta',
  badge:               'beta',
  notification:        'beta',
  snackbar:            'beta',
  'empty-state':       'beta',
  'status-bar':        'beta',
  'circular-progress': 'beta',
  'step-tracker':      'beta',
  section:             'beta',
  card:                'beta',
  stack:               'beta',
  grid:                'beta',
  bleed:               'beta',
  inset:               'beta',
  spacer:              'beta',
  'page-layout':       'beta',
  'button-container':  'beta',
  figure:              'beta',
  dialog:              'beta',
  overlay:             'beta',
  menu:                'beta',
  'context-menu':      'beta',
  tooltip:             'beta',
  'data-table':        'beta',
  'line-chart':        'experimental',
  'bar-chart':         'experimental',
  'area-chart':        'experimental',
  'composed-chart':    'experimental',
  'pie-chart':         'experimental',
  'scatter-chart':     'experimental',
  'radar-chart':       'experimental',
  'radial-bar-chart':  'experimental',
  'funnel-chart':      'experimental',
  'treemap-chart':     'experimental',
  'sankey-chart':      'experimental',
  'sunburst-chart':    'experimental',
  stat:                'experimental',
  'definition-list':   'beta',
  pagination:          'beta',
  calendar:            'experimental',
  canvas:              'experimental',
  node:                'experimental',
  icon:                'beta',
  accordion:           'beta',
}

export const STATUS_META = {
  stable:       { status: 'success', label: 'Stable',       icon: 'check_circle', desc: 'Production-ready. API is stable and fully documented.' },
  beta:         { status: 'warn',    label: 'Beta',         icon: 'science',    desc: 'Available for use. API may evolve before the stable release.' },
  experimental: { status: 'info',    label: 'Experimental', icon: 'science',    desc: 'Proof of concept. Breaking changes are expected.' },
  deprecated:   { status: 'error',   label: 'Deprecated',   icon: 'block',      desc: 'Scheduled for removal. Migrate to the recommended alternative.' },
}

// Related components — curated by usage patterns and natural substitution/composition.
export const COMPONENT_RELATED = {
  heading:             ['paragraph', 'divider', 'section'],
  paragraph:           ['heading', 'blockquote', 'inline'],
  blockquote:          ['paragraph', 'divider'],
  list:                ['paragraph', 'divider'],
  code:                ['paragraph', 'button'],
  divider:             ['spacer', 'section'],
  inline:              ['paragraph', 'text-field'],
  link:                ['button', 'breadcrumb', 'page-nav'],
  breadcrumb:          ['link', 'page-nav'],
  'side-nav':          ['top-header', 'page-layout'],
  'top-header':        ['side-nav', 'page-layout', 'menu'],
  'bottom-drawer':     ['top-header', 'tabs', 'page-layout'],
  tabs:                ['segmented-control', 'page-nav'],
  'page-nav':          ['tabs', 'breadcrumb'],
  'tree-menu':         ['side-nav', 'accordion', 'menu'],
  button:              ['icon-button', 'button-container', 'link'],
  'action-tile':       ['card', 'button', 'switch'],
  chip:                ['button', 'menu', 'segmented-control'],
  'icon-button':       ['button', 'icon'],
  switch:              ['checkbox-group', 'radio-group', 'segmented-control'],
  'segmented-control': ['tabs', 'switch', 'slider'],
  slider:              ['segmented-control', 'number-field', 'switch'],
  toolbar:             ['segmented-control', 'choice-group', 'sticky-actions'],
  'sticky-actions':    ['button', 'button-container', 'step-tracker'],
  'text-field':        ['number-field', 'search-field', 'select', 'textarea', 'fieldset'],
  'search-field':      ['text-field', 'autocomplete'],
  'number-field':      ['text-field', 'fieldset'],
  'date-field':        ['time-field', 'text-field', 'calendar'],
  'time-field':        ['date-field', 'text-field'],
  'phone-field':       ['text-field', 'zip-field'],
  'zip-field':         ['text-field', 'phone-field'],
  'credit-card-field': ['text-field', 'number-field'],
  textarea:            ['text-field', 'fieldset'],
  select:              ['text-field', 'radio-group'],
  autocomplete:        ['select', 'choice-group'],
  'checkbox-group':    ['radio-group', 'fieldset', 'switch'],
  'radio-group':       ['checkbox-group', 'fieldset', 'switch'],
  fieldset:            ['field-row', 'text-field', 'checkbox-group'],
  'field-row':         ['fieldset', 'text-field', 'select'],
  'inline-editable':   ['text-field', 'textarea'],
  'choice-group':      ['checkbox-group', 'radio-group', 'segmented-control'],
  banner:              ['empty-state', 'badge'],
  badge:               ['banner', 'notification'],
  notification:        ['badge', 'icon'],
  snackbar:            ['banner', 'badge'],
  'empty-state':       ['banner', 'button', 'section'],
  'status-bar':        ['circular-progress', 'step-tracker'],

  section:             ['card', 'grid', 'stack'],
  card:                ['section', 'grid'],
  stack:               ['grid', 'section'],
  grid:                ['stack', 'section'],
  bleed:               ['section', 'inset'],
  inset:               ['section', 'spacer'],
  spacer:              ['inset', 'stack'],
  'page-layout':       ['section', 'side-nav', 'top-header'],
  'button-container':  ['button', 'stack'],
  figure:              ['card', 'section'],
  dialog:              ['overlay', 'menu', 'button', 'tooltip'],
  overlay:             ['dialog', 'banner', 'snackbar'],
  menu:                ['dialog', 'context-menu', 'button', 'tooltip'],
  'context-menu':      ['menu', 'dialog', 'tooltip'],
  tooltip:             ['icon-button', 'button', 'menu'],
  'circular-progress': ['status-bar', 'badge', 'icon'],
  'step-tracker':      ['tabs', 'status-bar', 'circular-progress'],
  'data-table':        ['definition-list', 'pagination', 'section'],
  'line-chart':        ['bar-chart', 'area-chart', 'composed-chart', 'stat'],
  'bar-chart':         ['line-chart', 'area-chart', 'composed-chart', 'data-table'],
  'area-chart':        ['line-chart', 'bar-chart', 'composed-chart', 'stat'],
  'composed-chart':    ['line-chart', 'bar-chart', 'area-chart', 'scatter-chart'],
  'pie-chart':         ['radial-bar-chart', 'funnel-chart', 'treemap-chart', 'stat'],
  'scatter-chart':     ['line-chart', 'composed-chart', 'data-table', 'stat'],
  'radar-chart':       ['radial-bar-chart', 'line-chart', 'stat'],
  'radial-bar-chart':  ['pie-chart', 'radar-chart', 'funnel-chart'],
  'funnel-chart':      ['pie-chart', 'radial-bar-chart', 'sankey-chart'],
  'treemap-chart':     ['sunburst-chart', 'pie-chart', 'data-table'],
  'sankey-chart':      ['funnel-chart', 'treemap-chart', 'sunburst-chart'],
  'sunburst-chart':    ['treemap-chart', 'pie-chart', 'sankey-chart'],
  stat:                ['line-chart', 'bar-chart', 'data-table', 'definition-list', 'card'],
  'definition-list':   ['data-table', 'stat', 'heading', 'icon-button'],
  pagination:          ['data-table'],
  calendar:            ['data-table', 'definition-list', 'date-field', 'pagination'],
  canvas:              ['data-table', 'card', 'dialog'],
  icon:                ['icon-button', 'badge'],
  accordion:           ['tabs', 'section'],
}

export const ruleSourceFiles = [
  { file: 'system/rules/button.yaml', raw: buttonRules },
  { file: 'system/rules/action-tile.yaml', raw: actionTileRules },
  { file: 'system/rules/chip.yaml', raw: chipRules },
  { file: 'system/rules/card.yaml', raw: cardRules },
  { file: 'system/rules/page-layout.yaml', raw: pageLayoutRules },
  { file: 'system/rules/side-nav.yaml', raw: sideNavRules },
  { file: 'system/rules/message-badge.yaml', raw: messageBadgeRules },
  { file: 'system/rules/definition-list.yaml', raw: definitionListRules },
  { file: 'system/rules/circular-progress.yaml', raw: circularProgressRules },
  { file: 'system/rules/step-tracker.yaml', raw: stepTrackerRules },
  { file: 'system/rules/toolbar.yaml', raw: toolbarRules },
  { file: 'system/rules/section.yaml', raw: sectionRules },
  { file: 'system/rules/tooltip.yaml', raw: tooltipRules },
  { file: 'system/rules/overlay.yaml', raw: overlayRules },
  { file: 'system/rules/chart.yaml', raw: chartRules },
]
