import { mkdirSync, readdirSync, readFileSync, watch, writeFileSync } from 'node:fs';
import { dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';

const here = dirname(fileURLToPath(import.meta.url));
const pluginRoot = resolve(here, '..');
const repoRoot = resolve(pluginRoot, '../../../..');
const srcRoot = resolve(pluginRoot, 'src');
const pureRoot = resolve(srcRoot, 'pure');
const figmaRoot = resolve(srcRoot, 'figma');
const distRoot = resolve(pluginRoot, 'dist');

const codeSourcePath = resolve(srcRoot, 'code.js');
const uiSourcePath = resolve(srcRoot, 'ui.html');
const libraryManifestPath = resolve(pluginRoot, 'a1-library-manifest.json');
const codeDistPath = resolve(distRoot, 'code.js');
const uiDistPath = resolve(distRoot, 'ui.html');

const beginMarker = '/* == BEGIN A1 PURE (generated by sync-ui-css.mjs — do not edit) == */';
const endMarker = '/* == END A1 PURE == */';
const libraryManifestPlaceholder = '__A1_FIGMA_LIBRARY_MANIFEST__';
const localImportPattern = /^import\s+\{[^}]+\}\s+from\s+['"]((?:\.\/(?:pure|figma|adapters|shared)\/|\.\.\/\.\.\/\.\.\/shared\/)[^'"]+\.js)['"];\n/gm;

function read(path) {
  return readFileSync(path, 'utf8');
}

function stripImports(css) {
  return css
    .split('\n')
    .filter((line) => !line.trim().startsWith('@import'))
    .join('\n');
}

function generatedPureCssBlock() {
  const light = read(resolve(repoRoot, 'packages/pure/dist/a1-light.css'));
  const pure = stripImports(read(resolve(repoRoot, 'packages/pure/dist/a1-pure.css')));
  const tokens = read(resolve(repoRoot, 'build/css/tokens.css'));
  const shadows = tokens
    .split('\n')
    .filter((line) => line.trim().startsWith('--semantic-shadow-'))
    .join('\n');

  return [
    beginMarker,
    light.trim(),
    '/* Semantic shadows from build/css/tokens.css (not yet in the a1-light output) */',
    ':root {',
    shadows,
    '}',
    pure.trim(),
    endMarker,
  ].join('\n');
}

function renderUi() {
  const source = read(uiSourcePath);
  const start = source.indexOf(beginMarker);
  const end = source.indexOf(endMarker);
  assert.notEqual(start, -1, 'src/ui.html is missing the A1 Pure begin marker.');
  assert.notEqual(end, -1, 'src/ui.html is missing the A1 Pure end marker.');
  assert.ok(end > start, 'src/ui.html has malformed A1 Pure markers.');
  return source.slice(0, start) + generatedPureCssBlock() + source.slice(end + endMarker.length);
}

function renderCode() {
  const source = inlineLocalImports(read(codeSourcePath));
  assert.ok(
    source.includes(libraryManifestPlaceholder),
    `src/code.js is missing the ${libraryManifestPlaceholder} placeholder.`
  );
  JSON.parse(read(libraryManifestPath));
  return source.replace(libraryManifestPlaceholder, read(libraryManifestPath).trim());
}

function inlineLocalImports(source) {
  let modules = '';
  const stripped = source.replace(localImportPattern, (match, importPath) => {
    const modulePath = resolve(srcRoot, importPath);
    modules += `${read(modulePath)
      .replace(/^export\s+const\s+/gm, 'const ')
      .replace(/^export\s+async\s+function\s+/gm, 'async function ')
      .replace(/^export\s+function\s+/gm, 'function ')}\n`;
    return '';
  });
  return modules ? `${modules}\n${stripped}` : stripped;
}

function pureSourcePaths() {
  return readdirSync(pureRoot)
    .filter((file) => file.endsWith('.js'))
    .map((file) => resolve(pureRoot, file));
}

function figmaSourcePaths() {
  return readdirSync(figmaRoot)
    .filter((file) => file.endsWith('.js'))
    .map((file) => resolve(figmaRoot, file));
}

function adapterSourcePaths() {
  const adaptersRoot = resolve(srcRoot, 'adapters');
  return readdirSync(adaptersRoot)
    .filter((file) => file.endsWith('.js'))
    .map((file) => resolve(adaptersRoot, file));
}

function sharedSourcePaths() {
  const sharedRoot = resolve(srcRoot, 'shared');
  return readdirSync(sharedRoot)
    .filter((file) => file.endsWith('.js'))
    .map((file) => resolve(sharedRoot, file));
}

function renderOutputs() {
  return {
    [codeDistPath]: renderCode(),
    [uiDistPath]: renderUi(),
  };
}

function build() {
  mkdirSync(distRoot, { recursive: true });
  const outputs = renderOutputs();
  for (const [path, content] of Object.entries(outputs)) {
    writeFileSync(path, content);
  }
  console.log(`Built ${relative(repoRoot, codeDistPath)} and ${relative(repoRoot, uiDistPath)}.`);
}

function check() {
  const outputs = renderOutputs();
  const changed = Object.entries(outputs).filter(([path, expected]) => read(path) !== expected);
  if (changed.length > 0) {
    console.error('Generated Figma plugin output is stale:');
    for (const [path] of changed) console.error(`- ${relative(repoRoot, path)}`);
    process.exit(1);
  }
  console.log('Generated Figma plugin output is current.');
}

function watchBuild() {
  build();
  const watchedFiles = [
    codeSourcePath,
    uiSourcePath,
    ...pureSourcePaths(),
    ...figmaSourcePaths(),
    ...adapterSourcePaths(),
    ...sharedSourcePaths(),
    resolve(repoRoot, 'packages/pure/dist/a1-light.css'),
    resolve(repoRoot, 'packages/pure/dist/a1-pure.css'),
    resolve(repoRoot, 'build/css/tokens.css'),
    libraryManifestPath,
  ];
  for (const file of watchedFiles) {
    watch(file, { persistent: true }, () => {
      try {
        build();
      } catch (error) {
        console.error(error);
      }
    });
  }
  console.log('Watching A1:Figma plugin source and CSS inputs.');
}

if (process.argv.includes('--check')) {
  check();
} else if (process.argv.includes('--watch')) {
  watchBuild();
} else {
  build();
}
