export const foundations = [
  {
    id: 'foundation-system-map',
    title: 'System map',
    icon: 'hub',
    body: 'A live Canvas/Node visualization of how A1 fits together end to end: tokens as the root, themes/icons/labels/rules feeding the component library, and components composing into the pages, patterns, and projects of the a1-web editor.',
    points: ['Tokens → packages → components', 'Components → pages & patterns', 'Click to trace, drag to arrange'],
  },
  {
    id: 'foundation-color',
    title: 'Color',
    icon: 'palette',
    body: 'Color ramps, semantic color roles, status colors, surfaces, borders, action colors, inverse mode, and dark-mode behavior.',
    points: ['Base color ramps', 'Semantic text and surface roles', 'Status and action colors'],
  },
  {
    id: 'foundation-size',
    title: 'Size',
    icon: 'straighten',
    body: 'Spacing, dimensions, density, component sizing, icon sizing, touch targets, layout rhythm, and responsive scale decisions.',
    points: ['Spacing scale', 'Component dimensions', 'Responsive density'],
  },
  {
    id: 'foundation-type-scale',
    title: 'Type scale',
    icon: 'text_fields',
    body: 'Body, heading, and display type scales for readable interfaces across compact tools, editorial pages, and high-impact hero moments.',
    points: ['Body sizes', 'Heading sizes', 'Display sizes'],
  },
  {
    id: 'foundation-shape',
    title: 'Shape',
    icon: 'rounded_corner',
    body: 'Radius, container shape, control shape, card shape, dialog shape, and theme-specific geometry such as the heritage square profile.',
    points: ['Radius scale', 'Control corners', 'Container shape'],
  },
  {
    id: 'foundation-motion',
    title: 'Motion',
    icon: 'animation',
    body: 'Motion duration, easing, transition timing, and reduced-motion expectations for interactive components.',
    points: ['Duration scale', 'Easing roles', 'Reduced-motion behavior'],
  },
  {
    id: 'foundation-elevation',
    title: 'Elevation',
    icon: 'layers',
    body: 'Surface hierarchy, shadows, raised surfaces, panels, dialogs, menus, and the visual rules that separate content layers.',
    points: ['Surface hierarchy', 'Shadow tokens', 'Overlay depth'],
  },
  {
    id: 'foundation-iconography',
    title: 'Iconography',
    icon: 'interests',
    body: 'Material Symbols usage, icon sizing, optical size, weight, fill, and the rules for passing icon names into components.',
    points: ['Material Symbols', 'Icon name props', 'Optical sizing'],
  },
  {
    id: 'foundation-accessibility',
    title: 'Accessibility',
    icon: 'accessibility_new',
    body: 'Contrast, focus states, semantic markup, keyboard interaction, screen reader labels, and accessible component defaults.',
    points: ['Focus visibility', 'Semantic structure', 'Keyboard support'],
  },
  {
    id: 'foundation-labels',
    title: 'Labels',
    icon: 'translate',
    body: 'Localised UI strings used by A1 components. Every user-facing string is a named label with a default English value and per-locale translations.',
    points: ['Dot-notation label keys', 'Per-locale translations', 'LabelsProvider and useLabel hook'],
  },
  {
    id: 'foundation-responsive',
    title: 'Responsive',
    icon: 'devices',
    body: 'Viewport breakpoints for page-level layout and container query breakpoints for component-level adaptation. Both use T-shirt sizes (xs–xl) at values suited to their context.',
    points: ['Viewport breakpoints (media queries)', 'Container query breakpoints', 'Standard container query sizes'],
  },
  {
    id: 'foundation-prop-conventions',
    title: 'Prop conventions',
    icon: 'rule',
    body: 'Shared prop names and value sets used consistently across all A1 components. Use these when building or extending a component.',
    points: ['Size scales', 'Status, variant, and alignment values', 'Controlled state pattern'],
  },
  {
    id: 'foundation-z-index',
    title: 'Z-index',
    icon: 'filter_none',
    body: 'Layering and stacking: the browser top layer (modals) vs. the numeric z-index scale (sticky, pinned, popover, modal, toast). Where each element lives, and why a higher number can’t beat a modal.',
    points: ['Top layer vs. z-index scale', 'The layer scale (100 → 1200)', 'Component audit and rules'],
  },
  {
    id: 'foundation-utilities',
    title: 'Utilities',
    icon: 'style',
    body: 'Small, single-purpose class utilities for one-off adjustments — tokenised spacing (padding/margin/gap), min/max width, and screen-reader-only content. Reach for a layout component first; use a utility when no component covers the need.',
    points: ['Spacing and gap classes', 'Min/max width classes', 'Screen-reader only'],
  },
]
