// Inlines the A1 Pure library into the plugin UI (A1 styling showcase).
// Figma plugin iframes cannot load external stylesheets, so ui.html carries
// the real packages/pure/dist CSS between generated markers. Re-run after any
// token or a1-pure change:
//
//   npm run figma:plugin:sync-css
//
// Sources:
//   packages/pure/dist/a1-light.css   — token custom properties (light theme)
//   build/css/tokens.css              — semantic shadows (missing from the
//                                       a1-light output; see maintenance log)
//   packages/pure/dist/a1-pure.css    — scoped component classes (@imports
//                                       stripped: tokens are inlined above and
//                                       the Material Symbols font import would
//                                       be blocked by the plugin sandbox)
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '../../../..');
const uiPath = resolve(here, 'ui.html');

const BEGIN = '/* == BEGIN A1 PURE (generated by sync-ui-css.mjs — do not edit) == */';
const END = '/* == END A1 PURE == */';

const light = readFileSync(resolve(repoRoot, 'packages/pure/dist/a1-light.css'), 'utf8');
const pure = readFileSync(resolve(repoRoot, 'packages/pure/dist/a1-pure.css'), 'utf8')
  .split('\n')
  .filter((line) => !line.trim().startsWith('@import'))
  .join('\n');
const tokens = readFileSync(resolve(repoRoot, 'build/css/tokens.css'), 'utf8');
const shadows = tokens
  .split('\n')
  .filter((line) => line.trim().startsWith('--semantic-shadow-'))
  .join('\n');

const block = [
  BEGIN,
  light.trim(),
  '/* Semantic shadows from build/css/tokens.css (not yet in the a1-light output) */',
  ':root {',
  shadows,
  '}',
  pure.trim(),
  END,
].join('\n');

const ui = readFileSync(uiPath, 'utf8');
const start = ui.indexOf(BEGIN);
const end = ui.indexOf(END);
if (start === -1 || end === -1) {
  console.error('ui.html is missing the A1 PURE markers — refusing to write.');
  process.exit(1);
}
writeFileSync(uiPath, ui.slice(0, start) + block + ui.slice(end + END.length));
console.log(`Inlined A1 Pure CSS into ui.html (${Math.round(block.length / 1024)} KB).`);
