// Reads the Style Dictionary build output (already resolved to literal values)
// and flattens it into a lookup list of { path, cssVar, value } entries.
//
// Source: build/json/tokens.json — regenerated by `npm run build:tokens`.
// Do not read system/tokens/*.json directly here: those are unresolved DTCG
// source files with `{alias}` references; the build output is what components
// and CSS actually consume.

import fs from 'node:fs';
import { repoPath } from './paths.mjs';
import { flattenResolvedTree } from './token-shape.mjs';

export function parseTokens() {
  const tree = JSON.parse(fs.readFileSync(repoPath('build/json/tokens.json'), 'utf8'));
  return flattenResolvedTree(tree);
}
